# Extract

En esta etapa se extraen los datos originales del dataset de Netflix proporcionado por Kaggle y se cargan en un DataFrame de Pandas, sin realizar modificaciones.

In [3]:
%pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

# Cargar el dataset
df = pd.read_csv("netflix_titles.csv")

# Mostrar los primeros 5 registros
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

# Transform

### show_id

| Nombre de columna | Posibles riesgos |
|---|---|
| `show_id` | valor vacio, repeticion, no esten en orden, falten algunos|

### type

| Nombre de columna | Posibles riesgos |
|---|---|
| `type` | valor vacio, mal formato, valor sin sentido|

### title

| Nombre de columna | Posibles riesgos |
|---|---|
| `title` | valor null|

### director

| Nombre de columna | Posibles riesgos |
|---|---|
| `director` | valor null, mal formato (comas entre directores) |

### cast

| Nombre de columna | Posibles riesgos |
|---|---|
| `cast` | null, mal formato (comas entre cast) |


### country

| Nombre de columna | Posibles riesgos |
|---|---|
| `country` |null, mal formato (comas entrepaises) |
 

### date_added

| Nombre de columna | Posibles riesgos |
|---|---|
| `date_added` | null, formateo de la fecha|

### release_year

| Nombre de columna | Posibles riesgos |
|---|---|
| `release_year` | null, tipo de dato no numerico |

### rating

| Nombre de columna | Posibles riesgos |
|---|---|
| `rating` | null, formato|

### duration

| Nombre de columna | Posibles riesgos |
|---|---|
| `duration` | null, formato correcto, diferencia entre min y season|

### listed_in

| Nombre de columna | Posibles riesgos |
|---|---|
| `listed_in` | null, formato correcto de lista|

### description

| Nombre de columna | Posibles riesgos |
|---|---|
| `description` |null |

In [5]:
# Información general del dataset
df.info()

# Cantidad de valores nulos por columna
print("\n--- Valores nulos ---")
print(df.isnull().sum())

# Cantidad de valores duplicados
print("\n--- Filas duplicadas ---")
print(df.duplicated().sum())

# Valores únicos de columnas categóricas
print("\n--- Valores únicos: type ---")
print(df["type"].unique())

print("\n--- Valores únicos: rating ---")
print(df["rating"].unique())

# Cantidad de valores únicos en cada columna
print("\n--- Valores únicos por columna ---")
print(df.nunique())

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

--- Valores nulos ---
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

--- Filas duplicadas ---
0

--- Valores únicos: type ---
<StringArray>
['Movie', 'TV Show']
Length: 2, dtype: str

--- Valores únicos: rating ---
<StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',   '74 min',
   '84 min',   '66 min',       'NR',        nan, 'TV-Y7-FV',       'UR']
Length: 18, dtype: str

--- Valores únicos por columna ---
show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

In [6]:
df[df["rating"].isin(["74 min", "84 min", "66 min"])]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [7]:
# ============================================================
# TRANSFORM
# ============================================================

df_clean = df.copy()

# ------------------------------------------------------------
# 1. Corregir valores de duration almacenados en rating
# ------------------------------------------------------------
# Algunas filas contienen valores como "74 min", "84 min"
# y "66 min" en la columna rating, mientras que duration
# aparece como nulo.
#
# Estos valores corresponden a la duración de la película,
# por lo que los movemos de rating a duration.

duration_in_rating = df_clean["rating"].str.match(
    r"^\d+\s+min$",
    na=False
)

df_clean.loc[duration_in_rating, "duration"] = (
    df_clean.loc[duration_in_rating, "rating"]
)

df_clean.loc[duration_in_rating, "rating"] = pd.NA


# ------------------------------------------------------------
# 2. Convertir date_added a formato de fecha
# ------------------------------------------------------------
# date_added originalmente está almacenada como texto.
# La convertimos al tipo datetime para facilitar posteriores
# consultas y análisis por fecha.

df_clean["date_added"] = pd.to_datetime(
    df_clean["date_added"],
    errors="coerce"
)


# ------------------------------------------------------------
# 3. Estandarizar valores de texto
# ------------------------------------------------------------
# Eliminamos espacios innecesarios al inicio y al final
# de los valores de las columnas de texto.

text_columns = [
    "show_id",
    "type",
    "title",
    "director",
    "cast",
    "country",
    "rating",
    "duration",
    "listed_in",
    "description"
]

for column in text_columns:
    df_clean[column] = df_clean[column].str.strip()


# ------------------------------------------------------------
# 4. Estandarizar valores nulos
# ------------------------------------------------------------
# Convertimos cadenas vacías en valores nulos para evitar
# tener diferentes representaciones de información faltante.

df_clean[text_columns] = df_clean[text_columns].replace(
    r"^\s*$",
    pd.NA,
    regex=True
)


# ------------------------------------------------------------
# 5. Separar valores múltiples
# ------------------------------------------------------------
# Algunas columnas contienen varios valores dentro de una
# misma celda separados por comas.
#
# Ejemplo:
# "United States, Canada"
#
# Por ahora conservamos estos valores como listas.
# Posteriormente podrán convertirse en tablas relacionadas
# durante el diseño de la base de datos.

for column in ["director", "cast", "country", "listed_in"]:
    df_clean[column] = df_clean[column].apply(
        lambda x: [item.strip() for item in x.split(",")]
        if pd.notna(x) else pd.NA
    )


# ------------------------------------------------------------
# 6. Verificar el resultado de las transformaciones
# ------------------------------------------------------------

print("Dimensiones del dataset:", df_clean.shape)

print("\nTipos de datos:")
print(df_clean.dtypes)

print("\nValores nulos:")
print(df_clean.isnull().sum())

print("\nPrimeros 5 registros transformados:")
display(df_clean.head())

Dimensiones del dataset: (8807, 12)

Tipos de datos:
show_id                    str
type                       str
title                      str
director                object
cast                    object
country                 object
date_added      datetime64[us]
release_year             int64
rating                     str
duration                   str
listed_in               object
description                str
dtype: object

Valores nulos:
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        98
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

Primeros 5 registros transformados:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,[Kirsten Johnson],<NA>,[United States],2021-09-25,2020,PG-13,90 min,[Documentaries],"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,<NA>,"[Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...",[South Africa],2021-09-24,2021,TV-MA,2 Seasons,"[International TV Shows, TV Dramas, TV Mysteries]","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,[Julien Leclercq],"[Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nab...",<NA>,2021-09-24,2021,TV-MA,1 Season,"[Crime TV Shows, International TV Shows, TV Ac...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,<NA>,<NA>,<NA>,2021-09-24,2021,TV-MA,1 Season,"[Docuseries, Reality TV]","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,<NA>,"[Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...",[India],2021-09-24,2021,TV-MA,2 Seasons,"[International TV Shows, Romantic TV Shows, TV...",In a city of coaching centers known to train I...

In [8]:
# ============================================================
# VALIDACIÓN DEL DATASET DESPUÉS DE LA TRANSFORMACIÓN
# ============================================================

# 1. Información general
print("=== INFORMACIÓN GENERAL ===")
df_clean.info()

# 2. Valores nulos por columna
print("\n=== VALORES NULOS ===")
print(df_clean.isnull().sum().to_string())

# 3. Filas completamente duplicadas
print("\n=== FILAS DUPLICADAS ===")
print(df_clean.astype(str).duplicated().sum())

# 4. IDs duplicados
print("\n=== show_id DUPLICADOS ===")
print(df_clean["show_id"].duplicated().sum())

# 5. Valores de type
print("\n=== VALORES DE type ===")
print(df_clean["type"].value_counts(dropna=False))

# 6. Valores de rating
print("\n=== VALORES DE rating ===")
print(df_clean["rating"].value_counts(dropna=False).to_string())

# 7. Valores de duration
print("\n=== VALORES DE duration ===")
print(df_clean["duration"].value_counts(dropna=False).head(20).to_string())

# 8. Valores de release_year
print("\n=== release_year ===")
print(df_clean["release_year"].describe())

# 9. Verificar nuevamente si quedaron duraciones dentro de rating
print("\n=== DURACIONES QUE SIGUEN EN rating ===")

remaining_duration_in_rating = df_clean[
    df_clean["rating"].str.match(r"^\d+\s+min$", na=False)
]

print(remaining_duration_in_rating[
    ["show_id", "title", "rating", "duration"]
])

# 10. Revisar valores nulos de date_added
print("\n=== date_added NULOS ===")
print(df_clean[df_clean["date_added"].isna()][
    ["show_id", "title", "date_added"]
])

# 11. Mostrar los primeros registros transformados
print("\n=== PRIMEROS 5 REGISTROS ===")
display(df_clean.head())

=== INFORMACIÓN GENERAL ===
<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8709 non-null   datetime64[us]
 7   release_year  8807 non-null   int64
 8   rating        8800 non-null   str
 9   duration      8807 non-null   str
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   str
dtypes: datetime64[us](1), int64(1), object(4), str(6)
memory usage: 825.8+ KB

=== VALORES NULOS ===
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        98
release_year       0
rating             7
duration           0
listed_in          0
description        0

=== FILAS DUPLICADAS ===
0

=== show_id DUPLICADOS ===
0

=== VALORES DE type ===
type
Movie      6131
TV Show    2676
Name: count, dtype: int64

=== VALORES DE rating ===
rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
NaN            7
TV-Y7-FV       6
NC-17          3
UR             3

=== VALORES DE duration ===
duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
94 min        146
97 min        146
93 min        146
91 min        144
95 min        137
96 min        130
92 min        129
102 min       122
98 min        120
99 min        118
88 min        116
101 min       116
103 min       114
106 min       111
100 min       108
89 min        106

=== release_year ===
count    8807.000000
mean     2014.180198
std         8.819312
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2019.000000
max      2021.000000
Name: release_year, dtype: float64

=== DURACIONES QUE SIGUEN EN rating ===
Empty DataFrame
Columns: [show_id, title, rating, duration]
Index: []

=== date_added NULOS ===
     show_id                                        title date_added
6066   s6067  A Young Doctor's Notebook and Other Stories        NaT
6079   s6080                              Abnormal Summit        NaT
6174   s6175              Anthony Bourdain: Parts Unknown        NaT
6177   s6178                                     忍者ハットリくん        NaT
6213   s6214                                Bad Education        NaT
...      ...                                          ...        ...
8539   s8540                                   The Tudors        NaT
8557   s8558                                The West Wing        NaT
8684   s8685                                      Vroomiz        NaT
8712   s8713                   Weird Wonders of the World        NaT
8755   s8756                            Women Behind Bars        NaT

[98 rows x 3 columns]

=== PRIMEROS 5 REGISTROS ===

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,[Kirsten Johnson],<NA>,[United States],2021-09-25,2020,PG-13,90 min,[Documentaries],"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,<NA>,"[Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...",[South Africa],2021-09-24,2021,TV-MA,2 Seasons,"[International TV Shows, TV Dramas, TV Mysteries]","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,[Julien Leclercq],"[Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nab...",<NA>,2021-09-24,2021,TV-MA,1 Season,"[Crime TV Shows, International TV Shows, TV Ac...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,<NA>,<NA>,<NA>,2021-09-24,2021,TV-MA,1 Season,"[Docuseries, Reality TV]","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,<NA>,"[Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...",[India],2021-09-24,2021,TV-MA,2 Seasons,"[International TV Shows, Romantic TV Shows, TV...",In a city of coaching centers known to train I...

In [9]:
from collections import Counter

country_counts = Counter(
    country
    for countries in df_clean["country"].dropna()
    for country in countries
)

country_counts_df = pd.DataFrame(
    country_counts.items(),
    columns=["country", "count"]
).sort_values("country")

with pd.option_context("display.max_rows", None):
    display(country_counts_df)

                  country  count
28                             7
116           Afghanistan      1
91                Albania      1
40                Algeria      3
76                 Angola      1
24              Argentina     91
99                Armenia      1
11              Australia    160
61                Austria     12
110            Azerbaijan      1
101               Bahamas      1
69             Bangladesh      4
79                Belarus      1
19                Belgium     90
97                Bermuda      1
111              Botswana      1
32                 Brazil     97
39               Bulgaria     10
4            Burkina Faso      1
68               Cambodia      6
62               Cameroon      1
15                 Canada    445
71         Cayman Islands      2
66                  Chile     29
14                  China    162
35               Colombia     52
88                Croatia      4
105                  Cuba      1
83                 Cyprus      1
8          Czech Republic     22
46                Denmark     48
108    Dominican Republic      1
121          East Germany      1
98                Ecuador      1
45                  Egypt    117
7                Ethiopia      1
13                Finland     11
12                 France    393
92                Georgia      2
6                 Germany    226
3                   Ghana      5
33                 Greece     11
84              Guatemala      2
26              Hong Kong    105
51                Hungary     11
56                Iceland     11
2                   India   1046
44              Indonesia     90
89                   Iran      4
85                   Iraq      2
29                Ireland     46
37                 Israel     30
22                  Italy    100
113               Jamaica      1
16                  Japan    318
34                 Jordan      9
114            Kazakhstan      1
65                  Kenya      6
47                 Kuwait      8
103                Latvia      1
53                Lebanon     31
104         Liechtenstein      1
115             Lithuania      1
67             Luxembourg     12
86                 Malawi      1
49               Malaysia     26
74                  Malta      3
60              Mauritius      2
9                  Mexico    169
100              Mongolia      1
122            Montenegro      1
94                Morocco      6
78             Mozambique      1
75                Namibia      2
30                  Nepal      2
48            Netherlands     50
31            New Zealand     33
106             Nicaragua      1
17                Nigeria    103
58                 Norway     30
82               Pakistan     24
63              Palestine      1
119                Panama      1
87               Paraguay      1
77                   Peru     10
55            Philippines     83
41                 Poland     41
70               Portugal      6
81            Puerto Rico      1
59                  Qatar     10
23                Romania     14
27                 Russia     27
109                 Samoa      1
42           Saudi Arabia     13
72                Senegal      3
73                 Serbia      7
21              Singapore     41
95               Slovakia      1
107              Slovenia      3
117               Somalia      1
1            South Africa     62
20            South Korea    231
93           Soviet Union      3
18                  Spain    232
102             Sri Lanka      1
118                 Sudan      1
52                 Sweden     42
36            Switzerland     19
54                  Syria      3
38                 Taiwan     89
43               Thailand     70
10                 Turkey    113
120                Uganda      1
96                Ukraine      3
57   United Arab Emirates     37
5          United Kingdom    806
0           United States   3690
64                Uruguay     14
112          Vatican City      1
25              Venezuela      4
50                Vietnam      7
90           West Germany      5
80               Zimbabwe      3

In [10]:
%pip install requests

Requirement already satisfied: requests in ./.venv/lib/python3.14/site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.14/site-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.14/site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.14/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./.venv/lib/python3.14/site-packages (from requests) (2026.7.22)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [11]:
import requests

response = requests.get(
    "https://countriesnow.space/api/v0.1/countries/positions"
)

print(response.status_code)
print(response.json())

200
{'error': False, 'msg': 'countries and positions retrieved', 'data': [{'name': 'Afghanistan', 'iso2': 'AF', 'long': 65, 'lat': 33}, {'name': 'Albania', 'iso2': 'AL', 'long': 20, 'lat': 41}, {'name': 'Algeria', 'iso2': 'DZ', 'long': 3, 'lat': 28}, {'name': 'AmericanSamoa', 'iso2': 'AS', 'long': -170, 'lat': -14.3333}, {'name': 'Andorra', 'iso2': 'AD', 'long': 1.6, 'lat': 42.5}, {'name': 'Angola', 'iso2': 'AO', 'long': 18.5, 'lat': -12.5}, {'name': 'Anguilla', 'iso2': 'AI', 'long': -63.1667, 'lat': 18.25}, {'name': 'Antarctica', 'iso2': 'AQ', 'long': '0', 'lat': -90}, {'name': 'Antigua and Barbuda', 'iso2': 'AG', 'long': -61.8, 'lat': 17.05}, {'name': 'Argentina', 'iso2': 'AR', 'long': -64, 'lat': -34}, {'name': 'Armenia', 'iso2': 'AM', 'long': 45, 'lat': 40}, {'name': 'Aruba', 'iso2': 'AW', 'long': -69.9667, 'lat': 12.5}, {'name': 'Australia', 'iso2': 'AU', 'long': 133, 'lat': -27}, {'name': 'Austria', 'iso2': 'AT', 'long': 13.3333, 'lat': 47.3333}, {'name': 'Azerbaijan', 'iso2': 'AZ', 'long': 47.5, 'lat': 40.5}, {'name': 'Bahamas', 'iso2': 'BS', 'long': -76, 'lat': 24.25}, {'name': 'Bahrain', 'iso2': 'BH', 'long': 50.55, 'lat': 26}, {'name': 'Bangladesh', 'iso2': 'BD', 'long': 90, 'lat': 24}, {'name': 'Barbados', 'iso2': 'BB', 'long': -59.5333, 'lat': 13.1667}, {'name': 'Belarus', 'iso2': 'BY', 'long': 28, 'lat': 53}, {'name': 'Belgium', 'iso2': 'BE', 'long': 4, 'lat': 50.8333}, {'name': 'Belize', 'iso2': 'BZ', 'long': -88.75, 'lat': 17.25}, {'name': 'Benin', 'iso2': 'BJ', 'long': 2.25, 'lat': 9.5}, {'name': 'Bermuda', 'iso2': 'BM', 'long': -64.75, 'lat': 32.3333}, {'name': 'Bhutan', 'iso2': 'BT', 'long': 90.5, 'lat': 27.5}, {'name': 'Bolivia, Plurinational State of Bolivia', 'iso2': 'BO', 'long': -65, 'lat': -17}, {'name': 'Bosnia and Herzegovina', 'iso2': 'BA', 'long': 18, 'lat': 44}, {'name': 'Botswana', 'iso2': 'BW', 'long': 24, 'lat': -22}, {'name': 'Bouvet Island', 'iso2': 'BV', 'long': 3.4, 'lat': -54.4333}, {'name': 'Brazil', 'iso2': 'BR', 'long': -55, 'lat': -10}, {'name': 'British Indian Ocean Territory', 'iso2': 'IO', 'long': 71.5, 'lat': -6}, {'name': 'Brunei Darussalam', 'iso2': 'BN', 'long': 114.6667, 'lat': 4.5}, {'name': 'Bulgaria', 'iso2': 'BG', 'long': 25, 'lat': 43}, {'name': 'Burkina Faso', 'iso2': 'BF', 'long': -2, 'lat': 13}, {'name': 'Burundi', 'iso2': 'BI', 'long': 30, 'lat': -3.5}, {'name': 'Cambodia', 'iso2': 'KH', 'long': 105, 'lat': 13}, {'name': 'Cameroon', 'iso2': 'CM', 'long': 12, 'lat': 6}, {'name': 'Canada', 'iso2': 'CA', 'long': -95, 'lat': 60}, {'name': 'Cape Verde', 'iso2': 'CV', 'long': -24, 'lat': 16}, {'name': 'Cayman Islands', 'iso2': 'KY', 'long': -80.5, 'lat': 19.5}, {'name': 'Central African Republic', 'iso2': 'CF', 'long': 21, 'lat': 7}, {'name': 'Chad', 'iso2': 'TD', 'long': 19, 'lat': 15}, {'name': 'Chile', 'iso2': 'CL', 'long': -71, 'lat': -30}, {'name': 'China', 'iso2': 'CN', 'long': 105, 'lat': 35}, {'name': 'Christmas Island', 'iso2': 'CX', 'long': 105.6667, 'lat': -10.5}, {'name': 'Cocos (Keeling) Islands', 'iso2': 'CC', 'long': 96.8333, 'lat': -12.5}, {'name': 'Colombia', 'iso2': 'CO', 'long': -72, 'lat': 4}, {'name': 'Comoros', 'iso2': 'KM', 'long': 44.25, 'lat': -12.1667}, {'name': 'Congo', 'iso2': 'CG', 'long': 15, 'lat': -1}, {'name': 'Congo, The Democratic Republic of the', 'iso2': 'CD', 'long': 25, 'lat': '0'}, {'name': 'Cook Islands', 'iso2': 'CK', 'long': -159.7667, 'lat': -21.2333}, {'name': 'Costa Rica', 'iso2': 'CR', 'long': -84, 'lat': 10}, {'name': 'Ivory Coast', 'iso2': 'CI', 'long': -5, 'lat': 8}, {'name': 'Croatia', 'iso2': 'HR', 'long': 15.5, 'lat': 45.1667}, {'name': 'Cuba', 'iso2': 'CU', 'long': -80, 'lat': 21.5}, {'name': 'Cyprus', 'iso2': 'CY', 'long': 33, 'lat': 35}, {'name': 'Czech Republic', 'iso2': 'CZ', 'long': 15.5, 'lat': 49.75}, {'name': 'Denmark', 'iso2': 'DK', 'long': 10, 'lat': 56}, {'name': 'Djibouti', 'iso2': 'DJ', 'long': 43, 'lat': 11.5}, {'name': 'Dominica', 'iso2': 'DM', 'long': -61.3333, 'lat': 15.4167}, {'name': 'Dominican Republic', 'iso2': 'DO', 'long': -70.6667, 'lat': 19}, {'name': 'Ecuador', 'iso2': 'EC', 'long': -77.5, 'lat': -2}, {'name': 'Egypt', 'iso2': 'EG', 'long': 30, 'lat': 27}, {'name': 'El Salvador', 'iso2': 'SV', 'long': -88.9167, 'lat': 13.8333}, {'name': 'Equatorial Guinea', 'iso2': 'GQ', 'long': 10, 'lat': 2}, {'name': 'Eritrea', 'iso2': 'ER', 'long': 39, 'lat': 15}, {'name': 'Estonia', 'iso2': 'EE', 'long': 26, 'lat': 59}, {'name': 'Ethiopia', 'iso2': 'ET', 'long': 38, 'lat': 8}, {'name': 'Falkland Islands', 'iso2': 'FK', 'long': -59, 'lat': -51.75}, {'name': 'Faroe Islands', 'iso2': 'FO', 'long': -7, 'lat': 62}, {'name': 'Fiji', 'iso2': 'FJ', 'long': 175, 'lat': -18}, {'name': 'Finland', 'iso2': 'FI', 'long': 26, 'lat': 64}, {'name': 'France', 'iso2': 'FR', 'long': 2, 'lat': 46}, {'name': 'French Polynesia', 'iso2': 'PF', 'long': -140, 'lat': -15}, {'name': 'French Southern and Antarctic Lands', 'iso2': 'TF', 'long': 67, 'lat': -43}, {'name': 'Gabon', 'iso2': 'GA', 'long': 11.75, 'lat': -1}, {'name': 'Gambia', 'iso2': 'GM', 'long': -16.5667, 'lat': 13.4667}, {'name': 'Georgia', 'iso2': 'GE', 'long': 43.5, 'lat': 42}, {'name': 'Germany', 'iso2': 'DE', 'long': 9, 'lat': 51}, {'name': 'Ghana', 'iso2': 'GH', 'long': -2, 'lat': 8}, {'name': 'Gibraltar', 'iso2': 'GI', 'long': -5.3667, 'lat': 36.1833}, {'name': 'Greece', 'iso2': 'EL', 'long': 22, 'lat': 39}, {'name': 'Greenland', 'iso2': 'GL', 'long': -40, 'lat': 72}, {'name': 'Grenada', 'iso2': 'GD', 'long': -61.6667, 'lat': 12.1167}, {'name': 'Guadeloupe', 'iso2': 'GP', 'long': -61.5833, 'lat': 16.25}, {'name': 'Guam', 'iso2': 'GU', 'long': 144.7833, 'lat': 13.4667}, {'name': 'Guatemala', 'iso2': 'GT', 'long': -90.25, 'lat': 15.5}, {'name': 'Guernsey', 'iso2': 'GG', 'long': -2.56, 'lat': 49.5}, {'name': 'Guinea', 'iso2': 'GN', 'long': -10, 'lat': 11}, {'name': 'Guinea-Bissau', 'iso2': 'GW', 'long': -15, 'lat': 12}, {'name': 'Guyana', 'iso2': 'GY', 'long': -59, 'lat': 5}, {'name': 'Haiti', 'iso2': 'HT', 'long': -72.4167, 'lat': 19}, {'name': 'Heard Island and McDonald Islands', 'iso2': 'HM', 'long': 72.5167, 'lat': -53.1}, {'name': 'Vatican City State (Holy See)', 'iso2': 'VA', 'long': 12.45, 'lat': 41.9}, {'name': 'Honduras', 'iso2': 'HN', 'long': -86.5, 'lat': 15}, {'name': 'Hong Kong', 'iso2': 'HK', 'long': 114.1667, 'lat': 22.25}, {'name': 'Hungary', 'iso2': 'HU', 'long': 20, 'lat': 47}, {'name': 'Iceland', 'iso2': 'IS', 'long': -18, 'lat': 65}, {'name': 'India', 'iso2': 'IN', 'long': 77, 'lat': 20}, {'name': 'Indonesia', 'iso2': 'ID', 'long': 120, 'lat': -5}, {'name': 'Iran, Islamic Republic of', 'iso2': 'IR', 'long': 53, 'lat': 32}, {'name': 'Iraq', 'iso2': 'IQ', 'long': 44, 'lat': 33}, {'name': 'Ireland', 'iso2': 'IE', 'long': -8, 'lat': 53}, {'name': 'Isle of Man', 'iso2': 'IM', 'long': -4.55, 'lat': 54.23}, {'name': 'Israel', 'iso2': 'IL', 'long': 34.75, 'lat': 31.5}, {'name': 'Italy', 'iso2': 'IT', 'long': 12.8333, 'lat': 42.8333}, {'name': 'Jamaica', 'iso2': 'JM', 'long': -77.5, 'lat': 18.25}, {'name': 'Japan', 'iso2': 'JP', 'long': 138, 'lat': 36}, {'name': 'Jersey', 'iso2': 'JE', 'long': -2.13, 'lat': 49.21}, {'name': 'Jordan', 'iso2': 'JO', 'long': 36, 'lat': 31}, {'name': 'Kazakhstan', 'iso2': 'KZ', 'long': 68, 'lat': 48}, {'name': 'Kenya', 'iso2': 'KE', 'long': 38, 'lat': 1}, {'name': 'Kiribati', 'iso2': 'KI', 'long': 173, 'lat': 1.4167}, {'name': 'North Korea', 'iso2': 'KP', 'long': 127, 'lat': 40}, {'name': 'South Korea', 'iso2': 'KR', 'long': 127.5, 'lat': 37}, {'name': 'Kuwait', 'iso2': 'KW', 'long': 47.6581, 'lat': 29.3375}, {'name': 'Kyrgyzstan', 'iso2': 'KG', 'long': 75, 'lat': 41}, {'name': 'Laos', 'iso2': 'LA', 'long': 105, 'lat': 18}, {'name': 'Latvia', 'iso2': 'LV', 'long': 25, 'lat': 57}, {'name': 'Lebanon', 'iso2': 'LB', 'long': 35.8333, 'lat': 33.8333}, {'name': 'Lesotho', 'iso2': 'LS', 'long': 28.5, 'lat': -29.5}, {'name': 'Liberia', 'iso2': 'LR', 'long': -9.5, 'lat': 6.5}, {'name': 'Libyan Arab Jamahiriya', 'iso2': 'LY', 'long': 17, 'lat': 25}, {'name': 'Liechtenstein', 'iso2': 'LI', 'long': 9.5333, 'lat': 47.1667}, {'name': 'Lithuania', 'iso2': 'LT', 'long': 24, 'lat': 56}, {'name': 'Luxembourg', 'iso2': 'LU', 'long': 6.1667, 'lat': 49.75}, {'name': 'Macau', 'iso2': 'MO', 'long': 113.55, 'lat': 22.1667}, {'name': 'Macedonia, The Former Yugoslav Republic of', 'iso2': 'MK', 'long': 22, 'lat': 41.8333}, {'name': 'Madagascar', 'iso2': 'MG', 'long': 47, 'lat': -20}, {'name': 'Malawi', 'iso2': 'MW', 'long': 34, 'lat': -13.5}, {'name': 'Malaysia', 'iso2': 'MY', 'long': 112.5, 'lat': 2.5}, {'name': 'Maldives', 'iso2': 'MV', 'long': 73, 'lat': 3.25}, {'name': 'Mali', 'iso2': 'ML', 'long': -4, 'lat': 17}, {'name': 'Malta', 'iso2': 'MT', 'long': 14.5833, 'lat': 35.8333}, {'name': 'Marshall Islands', 'iso2': 'MH', 'long': 168, 'lat': 9}, {'name': 'Martinique', 'iso2': 'MQ', 'long': -61, 'lat': 14.6667}, {'name': 'Mauritania', 'iso2': 'MR', 'long': -12, 'lat': 20}, {'name': 'Mauritius', 'iso2': 'MU', 'long': 57.55, 'lat': -20.2833}, {'name': 'Mayotte', 'iso2': 'YT', 'long': 45.1667, 'lat': -12.8333}, {'name': 'Mexico', 'iso2': 'MX', 'long': -102, 'lat': 23}, {'name': 'Micronesia, Federated States of', 'iso2': 'FM', 'long': 158.25, 'lat': 6.9167}, {'name': 'Moldova, Republic of', 'iso2': 'MD', 'long': 29, 'lat': 47}, {'name': 'Monaco', 'iso2': 'MC', 'long': 7.4, 'lat': 43.7333}, {'name': 'Mongolia', 'iso2': 'MN', 'long': 105, 'lat': 46}, {'name': 'Montenegro', 'iso2': 'ME', 'long': 19, 'lat': 42}, {'name': 'Montserrat', 'iso2': 'MS', 'long': -62.2, 'lat': 16.75}, {'name': 'Morocco', 'iso2': 'MA', 'long': -5, 'lat': 32}, {'name': 'Mozambique', 'iso2': 'MZ', 'long': 35, 'lat': -18.25}, {'name': 'Myanmar', 'iso2': 'MM', 'long': 98, 'lat': 22}, {'name': 'Namibia', 'iso2': 'NA', 'long': 17, 'lat': -22}, {'name': 'Nauru', 'iso2': 'NR', 'long': 166.9167, 'lat': -0.5333}, {'name': 'Nepal', 'iso2': 'NP', 'long': 84, 'lat': 28}, {'name': 'Netherlands', 'iso2': 'NL', 'long': 5.75, 'lat': 52.5}, {'name': 'Netherlands Antilles', 'iso2': 'AN', 'long': -68.75, 'lat': 12.25}, {'name': 'New Caledonia', 'iso2': 'NC', 'long': 165.5, 'lat': -21.5}, {'name': 'New Zealand', 'iso2': 'NZ', 'long': 174, 'lat': -41}, {'name': 'Nicaragua', 'iso2': 'NI', 'long': -85, 'lat': 13}, {'name': 'Niger', 'iso2': 'NE', 'long': 8, 'lat': 16}, {'name': 'Nigeria', 'iso2': 'NG', 'long': 8, 'lat': 10}, {'name': 'Niue', 'iso2': 'NU', 'long': -169.8667, 'lat': -19.0333}, {'name': 'Norfolk Island', 'iso2': 'NF', 'long': 167.95, 'lat': -29.0333}, {'name': 'Northern Mariana Islands', 'iso2': 'MP', 'long': 145.75, 'lat': 15.2}, {'name': 'Norway', 'iso2': 'NO', 'long': 10, 'lat': 62}, {'name': 'Oman', 'iso2': 'OM', 'long': 57, 'lat': 21}, {'name': 'Pakistan', 'iso2': 'PK', 'long': 70, 'lat': 30}, {'name': 'Palau', 'iso2': 'PW', 'long': 134.5, 'lat': 7.5}, {'name': 'Palestinian Territory, Occupied', 'iso2': 'PS', 'long': 35.25, 'lat': 32}, {'name': 'Panama', 'iso2': 'PA', 'long': -80, 'lat': 9}, {'name': 'Papua New Guinea', 'iso2': 'PG', 'long': 147, 'lat': -6}, {'name': 'Paraguay', 'iso2': 'PY', 'long': -58, 'lat': -23}, {'name': 'Peru', 'iso2': 'PE', 'long': -76, 'lat': -10}, {'name': 'Philippines', 'iso2': 'PH', 'long': 122, 'lat': 13}, {'name': 'Pitcairn', 'iso2': 'PN', 'long': -127.4, 'lat': -24.7}, {'name': 'Poland', 'iso2': 'PL', 'long': 20, 'lat': 52}, {'name': 'Portugal', 'iso2': 'PT', 'long': -8, 'lat': 39.5}, {'name': 'Puerto Rico', 'iso2': 'PR', 'long': -66.5, 'lat': 18.25}, {'name': 'Qatar', 'iso2': 'QA', 'long': 51.25, 'lat': 25.5}, {'name': 'Réunion', 'iso2': 'RE', 'long': 55.6, 'lat': -21.1}, {'name': 'Romania', 'iso2': 'RO', 'long': 25, 'lat': 46}, {'name': 'Russia', 'iso2': 'RU', 'long': 100, 'lat': 60}, {'name': 'Rwanda', 'iso2': 'RW', 'long': 30, 'lat': -2}, {'name': 'Saint Helena, Ascension and Tristan Da Cunha', 'iso2': 'SH', 'long': -5.7, 'lat': -15.9333}, {'name': 'Saint Kitts and Nevis', 'iso2': 'KN', 'long': -62.75, 'lat': 17.3333}, {'name': 'Saint Lucia', 'iso2': 'LC', 'long': -61.1333, 'lat': 13.8833}, {'name': 'Saint Pierre and Miquelon', 'iso2': 'PM', 'long': -56.3333, 'lat': 46.8333}, {'name': 'Saint Vincent and the Grenadines', 'iso2': 'VC', 'long': -61.2, 'lat': 13.25}, {'name': 'Samoa', 'iso2': 'WS', 'long': -172.3333, 'lat': -13.5833}, {'name': 'San Marino', 'iso2': 'SM', 'long': 12.4167, 'lat': 43.7667}, {'name': 'Sao Tome and Principe', 'iso2': 'ST', 'long': 7, 'lat': 1}, {'name': 'Saudi Arabia', 'iso2': 'SA', 'long': 45, 'lat': 25}, {'name': 'Senegal', 'iso2': 'SN', 'long': -14, 'lat': 14}, {'name': 'Serbia', 'iso2': 'RS', 'long': 21, 'lat': 44}, {'name': 'Seychelles', 'iso2': 'SC', 'long': 55.6667, 'lat': -4.5833}, {'name': 'Sierra Leone', 'iso2': 'SL', 'long': -11.5, 'lat': 8.5}, {'name': 'Singapore', 'iso2': 'SG', 'long': 103.8, 'lat': 1.3667}, {'name': 'Slovakia', 'iso2': 'SK', 'long': 19.5, 'lat': 48.6667}, {'name': 'Slovenia', 'iso2': 'SI', 'long': 15, 'lat': 46}, {'name': 'Solomon Islands', 'iso2': 'SB', 'long': 159, 'lat': -8}, {'name': 'Somalia', 'iso2': 'SO', 'long': 49, 'lat': 10}, {'name': 'South Africa', 'iso2': 'ZA', 'long': 24, 'lat': -29}, {'name': 'South Georgia and the South Sandwich Islands', 'iso2': 'GS', 'long': -37, 'lat': -54.5}, {'name': 'Spain', 'iso2': 'ES', 'long': -4, 'lat': 40}, {'name': 'Sri Lanka', 'iso2': 'LK', 'long': 81, 'lat': 7}, {'name': 'Sudan', 'iso2': 'SD', 'long': 30, 'lat': 15}, {'name': 'Suriname', 'iso2': 'SR', 'long': -56, 'lat': 4}, {'name': 'Svalbard and Jan Mayen', 'iso2': 'SJ', 'long': 20, 'lat': 78}, {'name': 'Swaziland', 'iso2': 'SZ', 'long': 31.5, 'lat': -26.5}, {'name': 'Sweden', 'iso2': 'SE', 'long': 15, 'lat': 62}, {'name': 'Switzerland', 'iso2': 'CH', 'long': 8, 'lat': 47}, {'name': 'Syria', 'iso2': 'SY', 'long': 38, 'lat': 35}, {'name': 'Taiwan', 'iso2': 'TW', 'long': 121, 'lat': 23.5}, {'name': 'Tajikistan', 'iso2': 'TJ', 'long': 71, 'lat': 39}, {'name': 'Tanzania, United Republic of', 'iso2': 'TZ', 'long': 35, 'lat': -6}, {'name': 'Thailand', 'iso2': 'TH', 'long': 100, 'lat': 15}, {'name': 'Timor-Leste', 'iso2': 'TL', 'long': 125.5167, 'lat': -8.55}, {'name': 'Togo', 'iso2': 'TG', 'long': 1.1667, 'lat': 8}, {'name': 'Tokelau', 'iso2': 'TK', 'long': -172, 'lat': -9}, {'name': 'Tonga', 'iso2': 'TO', 'long': -175, 'lat': -20}, {'name': 'Trinidad and Tobago', 'iso2': 'TT', 'long': -61, 'lat': 11}, {'name': 'Tunisia', 'iso2': 'TN', 'long': 9, 'lat': 34}, {'name': 'Turkey', 'iso2': 'TR', 'long': 35, 'lat': 39}, {'name': 'Turkmenistan', 'iso2': 'TM', 'long': 60, 'lat': 40}, {'name': 'Turks and Caicos Islands', 'iso2': 'TC', 'long': -71.5833, 'lat': 21.75}, {'name': 'Tuvalu', 'iso2': 'TV', 'long': 178, 'lat': -8}, {'name': 'Uganda', 'iso2': 'UG', 'long': 32, 'lat': 1}, {'name': 'Ukraine', 'iso2': 'UA', 'long': 32, 'lat': 49}, {'name': 'United Arab Emirates', 'iso2': 'AE', 'long': 54, 'lat': 24}, {'name': 'United Kingdom', 'iso2': 'GB', 'long': -2, 'lat': 54}, {'name': 'United States', 'iso2': 'US', 'long': -97, 'lat': 38}, {'name': 'United States Minor Outlying Islands', 'iso2': 'UM', 'long': 166.6, 'lat': 19.2833}, {'name': 'Uruguay', 'iso2': 'UY', 'long': -56, 'lat': -33}, {'name': 'Uzbekistan', 'iso2': 'UZ', 'long': 64, 'lat': 41}, {'name': 'Vanuatu', 'iso2': 'VU', 'long': 167, 'lat': -16}, {'name': 'Venezuela, Bolivarian Republic of', 'iso2': 'VE', 'long': -66, 'lat': 8}, {'name': 'Vietnam', 'iso2': 'VN', 'long': 106, 'lat': 16}, {'name': 'Virgin Islands, British', 'iso2': 'VG', 'long': -64.5, 'lat': 18.5}, {'name': 'Virgin Islands, U.S.', 'iso2': 'VI', 'long': -64.8333, 'lat': 18.3333}, {'name': 'Wallis and Futuna', 'iso2': 'WF', 'long': -176.2, 'lat': -13.3}, {'name': 'Western Sahara', 'iso2': 'EH', 'long': -13, 'lat': 24.5}, {'name': 'Yemen', 'iso2': 'YE', 'long': 48, 'lat': 15}, {'name': 'Zambia', 'iso2': 'ZM', 'long': 30, 'lat': -15}, {'name': 'Zimbabwe', 'iso2': 'ZW', 'long': 30, 'lat': -20}]}

In [12]:
countries_api = response.json()['data']

print(len(countries_api))
print(countries_api)

242
[{'name': 'Afghanistan', 'iso2': 'AF', 'long': 65, 'lat': 33}, {'name': 'Albania', 'iso2': 'AL', 'long': 20, 'lat': 41}, {'name': 'Algeria', 'iso2': 'DZ', 'long': 3, 'lat': 28}, {'name': 'AmericanSamoa', 'iso2': 'AS', 'long': -170, 'lat': -14.3333}, {'name': 'Andorra', 'iso2': 'AD', 'long': 1.6, 'lat': 42.5}, {'name': 'Angola', 'iso2': 'AO', 'long': 18.5, 'lat': -12.5}, {'name': 'Anguilla', 'iso2': 'AI', 'long': -63.1667, 'lat': 18.25}, {'name': 'Antarctica', 'iso2': 'AQ', 'long': '0', 'lat': -90}, {'name': 'Antigua and Barbuda', 'iso2': 'AG', 'long': -61.8, 'lat': 17.05}, {'name': 'Argentina', 'iso2': 'AR', 'long': -64, 'lat': -34}, {'name': 'Armenia', 'iso2': 'AM', 'long': 45, 'lat': 40}, {'name': 'Aruba', 'iso2': 'AW', 'long': -69.9667, 'lat': 12.5}, {'name': 'Australia', 'iso2': 'AU', 'long': 133, 'lat': -27}, {'name': 'Austria', 'iso2': 'AT', 'long': 13.3333, 'lat': 47.3333}, {'name': 'Azerbaijan', 'iso2': 'AZ', 'long': 47.5, 'lat': 40.5}, {'name': 'Bahamas', 'iso2': 'BS', 'long': -76, 'lat': 24.25}, {'name': 'Bahrain', 'iso2': 'BH', 'long': 50.55, 'lat': 26}, {'name': 'Bangladesh', 'iso2': 'BD', 'long': 90, 'lat': 24}, {'name': 'Barbados', 'iso2': 'BB', 'long': -59.5333, 'lat': 13.1667}, {'name': 'Belarus', 'iso2': 'BY', 'long': 28, 'lat': 53}, {'name': 'Belgium', 'iso2': 'BE', 'long': 4, 'lat': 50.8333}, {'name': 'Belize', 'iso2': 'BZ', 'long': -88.75, 'lat': 17.25}, {'name': 'Benin', 'iso2': 'BJ', 'long': 2.25, 'lat': 9.5}, {'name': 'Bermuda', 'iso2': 'BM', 'long': -64.75, 'lat': 32.3333}, {'name': 'Bhutan', 'iso2': 'BT', 'long': 90.5, 'lat': 27.5}, {'name': 'Bolivia, Plurinational State of Bolivia', 'iso2': 'BO', 'long': -65, 'lat': -17}, {'name': 'Bosnia and Herzegovina', 'iso2': 'BA', 'long': 18, 'lat': 44}, {'name': 'Botswana', 'iso2': 'BW', 'long': 24, 'lat': -22}, {'name': 'Bouvet Island', 'iso2': 'BV', 'long': 3.4, 'lat': -54.4333}, {'name': 'Brazil', 'iso2': 'BR', 'long': -55, 'lat': -10}, {'name': 'British Indian Ocean Territory', 'iso2': 'IO', 'long': 71.5, 'lat': -6}, {'name': 'Brunei Darussalam', 'iso2': 'BN', 'long': 114.6667, 'lat': 4.5}, {'name': 'Bulgaria', 'iso2': 'BG', 'long': 25, 'lat': 43}, {'name': 'Burkina Faso', 'iso2': 'BF', 'long': -2, 'lat': 13}, {'name': 'Burundi', 'iso2': 'BI', 'long': 30, 'lat': -3.5}, {'name': 'Cambodia', 'iso2': 'KH', 'long': 105, 'lat': 13}, {'name': 'Cameroon', 'iso2': 'CM', 'long': 12, 'lat': 6}, {'name': 'Canada', 'iso2': 'CA', 'long': -95, 'lat': 60}, {'name': 'Cape Verde', 'iso2': 'CV', 'long': -24, 'lat': 16}, {'name': 'Cayman Islands', 'iso2': 'KY', 'long': -80.5, 'lat': 19.5}, {'name': 'Central African Republic', 'iso2': 'CF', 'long': 21, 'lat': 7}, {'name': 'Chad', 'iso2': 'TD', 'long': 19, 'lat': 15}, {'name': 'Chile', 'iso2': 'CL', 'long': -71, 'lat': -30}, {'name': 'China', 'iso2': 'CN', 'long': 105, 'lat': 35}, {'name': 'Christmas Island', 'iso2': 'CX', 'long': 105.6667, 'lat': -10.5}, {'name': 'Cocos (Keeling) Islands', 'iso2': 'CC', 'long': 96.8333, 'lat': -12.5}, {'name': 'Colombia', 'iso2': 'CO', 'long': -72, 'lat': 4}, {'name': 'Comoros', 'iso2': 'KM', 'long': 44.25, 'lat': -12.1667}, {'name': 'Congo', 'iso2': 'CG', 'long': 15, 'lat': -1}, {'name': 'Congo, The Democratic Republic of the', 'iso2': 'CD', 'long': 25, 'lat': '0'}, {'name': 'Cook Islands', 'iso2': 'CK', 'long': -159.7667, 'lat': -21.2333}, {'name': 'Costa Rica', 'iso2': 'CR', 'long': -84, 'lat': 10}, {'name': 'Ivory Coast', 'iso2': 'CI', 'long': -5, 'lat': 8}, {'name': 'Croatia', 'iso2': 'HR', 'long': 15.5, 'lat': 45.1667}, {'name': 'Cuba', 'iso2': 'CU', 'long': -80, 'lat': 21.5}, {'name': 'Cyprus', 'iso2': 'CY', 'long': 33, 'lat': 35}, {'name': 'Czech Republic', 'iso2': 'CZ', 'long': 15.5, 'lat': 49.75}, {'name': 'Denmark', 'iso2': 'DK', 'long': 10, 'lat': 56}, {'name': 'Djibouti', 'iso2': 'DJ', 'long': 43, 'lat': 11.5}, {'name': 'Dominica', 'iso2': 'DM', 'long': -61.3333, 'lat': 15.4167}, {'name': 'Dominican Republic', 'iso2': 'DO', 'long': -70.6667, 'lat': 19}, {'name': 'Ecuador', 'iso2': 'EC', 'long': -77.5, 'lat': -2}, {'name': 'Egypt', 'iso2': 'EG', 'long': 30, 'lat': 27}, {'name': 'El Salvador', 'iso2': 'SV', 'long': -88.9167, 'lat': 13.8333}, {'name': 'Equatorial Guinea', 'iso2': 'GQ', 'long': 10, 'lat': 2}, {'name': 'Eritrea', 'iso2': 'ER', 'long': 39, 'lat': 15}, {'name': 'Estonia', 'iso2': 'EE', 'long': 26, 'lat': 59}, {'name': 'Ethiopia', 'iso2': 'ET', 'long': 38, 'lat': 8}, {'name': 'Falkland Islands', 'iso2': 'FK', 'long': -59, 'lat': -51.75}, {'name': 'Faroe Islands', 'iso2': 'FO', 'long': -7, 'lat': 62}, {'name': 'Fiji', 'iso2': 'FJ', 'long': 175, 'lat': -18}, {'name': 'Finland', 'iso2': 'FI', 'long': 26, 'lat': 64}, {'name': 'France', 'iso2': 'FR', 'long': 2, 'lat': 46}, {'name': 'French Polynesia', 'iso2': 'PF', 'long': -140, 'lat': -15}, {'name': 'French Southern and Antarctic Lands', 'iso2': 'TF', 'long': 67, 'lat': -43}, {'name': 'Gabon', 'iso2': 'GA', 'long': 11.75, 'lat': -1}, {'name': 'Gambia', 'iso2': 'GM', 'long': -16.5667, 'lat': 13.4667}, {'name': 'Georgia', 'iso2': 'GE', 'long': 43.5, 'lat': 42}, {'name': 'Germany', 'iso2': 'DE', 'long': 9, 'lat': 51}, {'name': 'Ghana', 'iso2': 'GH', 'long': -2, 'lat': 8}, {'name': 'Gibraltar', 'iso2': 'GI', 'long': -5.3667, 'lat': 36.1833}, {'name': 'Greece', 'iso2': 'EL', 'long': 22, 'lat': 39}, {'name': 'Greenland', 'iso2': 'GL', 'long': -40, 'lat': 72}, {'name': 'Grenada', 'iso2': 'GD', 'long': -61.6667, 'lat': 12.1167}, {'name': 'Guadeloupe', 'iso2': 'GP', 'long': -61.5833, 'lat': 16.25}, {'name': 'Guam', 'iso2': 'GU', 'long': 144.7833, 'lat': 13.4667}, {'name': 'Guatemala', 'iso2': 'GT', 'long': -90.25, 'lat': 15.5}, {'name': 'Guernsey', 'iso2': 'GG', 'long': -2.56, 'lat': 49.5}, {'name': 'Guinea', 'iso2': 'GN', 'long': -10, 'lat': 11}, {'name': 'Guinea-Bissau', 'iso2': 'GW', 'long': -15, 'lat': 12}, {'name': 'Guyana', 'iso2': 'GY', 'long': -59, 'lat': 5}, {'name': 'Haiti', 'iso2': 'HT', 'long': -72.4167, 'lat': 19}, {'name': 'Heard Island and McDonald Islands', 'iso2': 'HM', 'long': 72.5167, 'lat': -53.1}, {'name': 'Vatican City State (Holy See)', 'iso2': 'VA', 'long': 12.45, 'lat': 41.9}, {'name': 'Honduras', 'iso2': 'HN', 'long': -86.5, 'lat': 15}, {'name': 'Hong Kong', 'iso2': 'HK', 'long': 114.1667, 'lat': 22.25}, {'name': 'Hungary', 'iso2': 'HU', 'long': 20, 'lat': 47}, {'name': 'Iceland', 'iso2': 'IS', 'long': -18, 'lat': 65}, {'name': 'India', 'iso2': 'IN', 'long': 77, 'lat': 20}, {'name': 'Indonesia', 'iso2': 'ID', 'long': 120, 'lat': -5}, {'name': 'Iran, Islamic Republic of', 'iso2': 'IR', 'long': 53, 'lat': 32}, {'name': 'Iraq', 'iso2': 'IQ', 'long': 44, 'lat': 33}, {'name': 'Ireland', 'iso2': 'IE', 'long': -8, 'lat': 53}, {'name': 'Isle of Man', 'iso2': 'IM', 'long': -4.55, 'lat': 54.23}, {'name': 'Israel', 'iso2': 'IL', 'long': 34.75, 'lat': 31.5}, {'name': 'Italy', 'iso2': 'IT', 'long': 12.8333, 'lat': 42.8333}, {'name': 'Jamaica', 'iso2': 'JM', 'long': -77.5, 'lat': 18.25}, {'name': 'Japan', 'iso2': 'JP', 'long': 138, 'lat': 36}, {'name': 'Jersey', 'iso2': 'JE', 'long': -2.13, 'lat': 49.21}, {'name': 'Jordan', 'iso2': 'JO', 'long': 36, 'lat': 31}, {'name': 'Kazakhstan', 'iso2': 'KZ', 'long': 68, 'lat': 48}, {'name': 'Kenya', 'iso2': 'KE', 'long': 38, 'lat': 1}, {'name': 'Kiribati', 'iso2': 'KI', 'long': 173, 'lat': 1.4167}, {'name': 'North Korea', 'iso2': 'KP', 'long': 127, 'lat': 40}, {'name': 'South Korea', 'iso2': 'KR', 'long': 127.5, 'lat': 37}, {'name': 'Kuwait', 'iso2': 'KW', 'long': 47.6581, 'lat': 29.3375}, {'name': 'Kyrgyzstan', 'iso2': 'KG', 'long': 75, 'lat': 41}, {'name': 'Laos', 'iso2': 'LA', 'long': 105, 'lat': 18}, {'name': 'Latvia', 'iso2': 'LV', 'long': 25, 'lat': 57}, {'name': 'Lebanon', 'iso2': 'LB', 'long': 35.8333, 'lat': 33.8333}, {'name': 'Lesotho', 'iso2': 'LS', 'long': 28.5, 'lat': -29.5}, {'name': 'Liberia', 'iso2': 'LR', 'long': -9.5, 'lat': 6.5}, {'name': 'Libyan Arab Jamahiriya', 'iso2': 'LY', 'long': 17, 'lat': 25}, {'name': 'Liechtenstein', 'iso2': 'LI', 'long': 9.5333, 'lat': 47.1667}, {'name': 'Lithuania', 'iso2': 'LT', 'long': 24, 'lat': 56}, {'name': 'Luxembourg', 'iso2': 'LU', 'long': 6.1667, 'lat': 49.75}, {'name': 'Macau', 'iso2': 'MO', 'long': 113.55, 'lat': 22.1667}, {'name': 'Macedonia, The Former Yugoslav Republic of', 'iso2': 'MK', 'long': 22, 'lat': 41.8333}, {'name': 'Madagascar', 'iso2': 'MG', 'long': 47, 'lat': -20}, {'name': 'Malawi', 'iso2': 'MW', 'long': 34, 'lat': -13.5}, {'name': 'Malaysia', 'iso2': 'MY', 'long': 112.5, 'lat': 2.5}, {'name': 'Maldives', 'iso2': 'MV', 'long': 73, 'lat': 3.25}, {'name': 'Mali', 'iso2': 'ML', 'long': -4, 'lat': 17}, {'name': 'Malta', 'iso2': 'MT', 'long': 14.5833, 'lat': 35.8333}, {'name': 'Marshall Islands', 'iso2': 'MH', 'long': 168, 'lat': 9}, {'name': 'Martinique', 'iso2': 'MQ', 'long': -61, 'lat': 14.6667}, {'name': 'Mauritania', 'iso2': 'MR', 'long': -12, 'lat': 20}, {'name': 'Mauritius', 'iso2': 'MU', 'long': 57.55, 'lat': -20.2833}, {'name': 'Mayotte', 'iso2': 'YT', 'long': 45.1667, 'lat': -12.8333}, {'name': 'Mexico', 'iso2': 'MX', 'long': -102, 'lat': 23}, {'name': 'Micronesia, Federated States of', 'iso2': 'FM', 'long': 158.25, 'lat': 6.9167}, {'name': 'Moldova, Republic of', 'iso2': 'MD', 'long': 29, 'lat': 47}, {'name': 'Monaco', 'iso2': 'MC', 'long': 7.4, 'lat': 43.7333}, {'name': 'Mongolia', 'iso2': 'MN', 'long': 105, 'lat': 46}, {'name': 'Montenegro', 'iso2': 'ME', 'long': 19, 'lat': 42}, {'name': 'Montserrat', 'iso2': 'MS', 'long': -62.2, 'lat': 16.75}, {'name': 'Morocco', 'iso2': 'MA', 'long': -5, 'lat': 32}, {'name': 'Mozambique', 'iso2': 'MZ', 'long': 35, 'lat': -18.25}, {'name': 'Myanmar', 'iso2': 'MM', 'long': 98, 'lat': 22}, {'name': 'Namibia', 'iso2': 'NA', 'long': 17, 'lat': -22}, {'name': 'Nauru', 'iso2': 'NR', 'long': 166.9167, 'lat': -0.5333}, {'name': 'Nepal', 'iso2': 'NP', 'long': 84, 'lat': 28}, {'name': 'Netherlands', 'iso2': 'NL', 'long': 5.75, 'lat': 52.5}, {'name': 'Netherlands Antilles', 'iso2': 'AN', 'long': -68.75, 'lat': 12.25}, {'name': 'New Caledonia', 'iso2': 'NC', 'long': 165.5, 'lat': -21.5}, {'name': 'New Zealand', 'iso2': 'NZ', 'long': 174, 'lat': -41}, {'name': 'Nicaragua', 'iso2': 'NI', 'long': -85, 'lat': 13}, {'name': 'Niger', 'iso2': 'NE', 'long': 8, 'lat': 16}, {'name': 'Nigeria', 'iso2': 'NG', 'long': 8, 'lat': 10}, {'name': 'Niue', 'iso2': 'NU', 'long': -169.8667, 'lat': -19.0333}, {'name': 'Norfolk Island', 'iso2': 'NF', 'long': 167.95, 'lat': -29.0333}, {'name': 'Northern Mariana Islands', 'iso2': 'MP', 'long': 145.75, 'lat': 15.2}, {'name': 'Norway', 'iso2': 'NO', 'long': 10, 'lat': 62}, {'name': 'Oman', 'iso2': 'OM', 'long': 57, 'lat': 21}, {'name': 'Pakistan', 'iso2': 'PK', 'long': 70, 'lat': 30}, {'name': 'Palau', 'iso2': 'PW', 'long': 134.5, 'lat': 7.5}, {'name': 'Palestinian Territory, Occupied', 'iso2': 'PS', 'long': 35.25, 'lat': 32}, {'name': 'Panama', 'iso2': 'PA', 'long': -80, 'lat': 9}, {'name': 'Papua New Guinea', 'iso2': 'PG', 'long': 147, 'lat': -6}, {'name': 'Paraguay', 'iso2': 'PY', 'long': -58, 'lat': -23}, {'name': 'Peru', 'iso2': 'PE', 'long': -76, 'lat': -10}, {'name': 'Philippines', 'iso2': 'PH', 'long': 122, 'lat': 13}, {'name': 'Pitcairn', 'iso2': 'PN', 'long': -127.4, 'lat': -24.7}, {'name': 'Poland', 'iso2': 'PL', 'long': 20, 'lat': 52}, {'name': 'Portugal', 'iso2': 'PT', 'long': -8, 'lat': 39.5}, {'name': 'Puerto Rico', 'iso2': 'PR', 'long': -66.5, 'lat': 18.25}, {'name': 'Qatar', 'iso2': 'QA', 'long': 51.25, 'lat': 25.5}, {'name': 'Réunion', 'iso2': 'RE', 'long': 55.6, 'lat': -21.1}, {'name': 'Romania', 'iso2': 'RO', 'long': 25, 'lat': 46}, {'name': 'Russia', 'iso2': 'RU', 'long': 100, 'lat': 60}, {'name': 'Rwanda', 'iso2': 'RW', 'long': 30, 'lat': -2}, {'name': 'Saint Helena, Ascension and Tristan Da Cunha', 'iso2': 'SH', 'long': -5.7, 'lat': -15.9333}, {'name': 'Saint Kitts and Nevis', 'iso2': 'KN', 'long': -62.75, 'lat': 17.3333}, {'name': 'Saint Lucia', 'iso2': 'LC', 'long': -61.1333, 'lat': 13.8833}, {'name': 'Saint Pierre and Miquelon', 'iso2': 'PM', 'long': -56.3333, 'lat': 46.8333}, {'name': 'Saint Vincent and the Grenadines', 'iso2': 'VC', 'long': -61.2, 'lat': 13.25}, {'name': 'Samoa', 'iso2': 'WS', 'long': -172.3333, 'lat': -13.5833}, {'name': 'San Marino', 'iso2': 'SM', 'long': 12.4167, 'lat': 43.7667}, {'name': 'Sao Tome and Principe', 'iso2': 'ST', 'long': 7, 'lat': 1}, {'name': 'Saudi Arabia', 'iso2': 'SA', 'long': 45, 'lat': 25}, {'name': 'Senegal', 'iso2': 'SN', 'long': -14, 'lat': 14}, {'name': 'Serbia', 'iso2': 'RS', 'long': 21, 'lat': 44}, {'name': 'Seychelles', 'iso2': 'SC', 'long': 55.6667, 'lat': -4.5833}, {'name': 'Sierra Leone', 'iso2': 'SL', 'long': -11.5, 'lat': 8.5}, {'name': 'Singapore', 'iso2': 'SG', 'long': 103.8, 'lat': 1.3667}, {'name': 'Slovakia', 'iso2': 'SK', 'long': 19.5, 'lat': 48.6667}, {'name': 'Slovenia', 'iso2': 'SI', 'long': 15, 'lat': 46}, {'name': 'Solomon Islands', 'iso2': 'SB', 'long': 159, 'lat': -8}, {'name': 'Somalia', 'iso2': 'SO', 'long': 49, 'lat': 10}, {'name': 'South Africa', 'iso2': 'ZA', 'long': 24, 'lat': -29}, {'name': 'South Georgia and the South Sandwich Islands', 'iso2': 'GS', 'long': -37, 'lat': -54.5}, {'name': 'Spain', 'iso2': 'ES', 'long': -4, 'lat': 40}, {'name': 'Sri Lanka', 'iso2': 'LK', 'long': 81, 'lat': 7}, {'name': 'Sudan', 'iso2': 'SD', 'long': 30, 'lat': 15}, {'name': 'Suriname', 'iso2': 'SR', 'long': -56, 'lat': 4}, {'name': 'Svalbard and Jan Mayen', 'iso2': 'SJ', 'long': 20, 'lat': 78}, {'name': 'Swaziland', 'iso2': 'SZ', 'long': 31.5, 'lat': -26.5}, {'name': 'Sweden', 'iso2': 'SE', 'long': 15, 'lat': 62}, {'name': 'Switzerland', 'iso2': 'CH', 'long': 8, 'lat': 47}, {'name': 'Syria', 'iso2': 'SY', 'long': 38, 'lat': 35}, {'name': 'Taiwan', 'iso2': 'TW', 'long': 121, 'lat': 23.5}, {'name': 'Tajikistan', 'iso2': 'TJ', 'long': 71, 'lat': 39}, {'name': 'Tanzania, United Republic of', 'iso2': 'TZ', 'long': 35, 'lat': -6}, {'name': 'Thailand', 'iso2': 'TH', 'long': 100, 'lat': 15}, {'name': 'Timor-Leste', 'iso2': 'TL', 'long': 125.5167, 'lat': -8.55}, {'name': 'Togo', 'iso2': 'TG', 'long': 1.1667, 'lat': 8}, {'name': 'Tokelau', 'iso2': 'TK', 'long': -172, 'lat': -9}, {'name': 'Tonga', 'iso2': 'TO', 'long': -175, 'lat': -20}, {'name': 'Trinidad and Tobago', 'iso2': 'TT', 'long': -61, 'lat': 11}, {'name': 'Tunisia', 'iso2': 'TN', 'long': 9, 'lat': 34}, {'name': 'Turkey', 'iso2': 'TR', 'long': 35, 'lat': 39}, {'name': 'Turkmenistan', 'iso2': 'TM', 'long': 60, 'lat': 40}, {'name': 'Turks and Caicos Islands', 'iso2': 'TC', 'long': -71.5833, 'lat': 21.75}, {'name': 'Tuvalu', 'iso2': 'TV', 'long': 178, 'lat': -8}, {'name': 'Uganda', 'iso2': 'UG', 'long': 32, 'lat': 1}, {'name': 'Ukraine', 'iso2': 'UA', 'long': 32, 'lat': 49}, {'name': 'United Arab Emirates', 'iso2': 'AE', 'long': 54, 'lat': 24}, {'name': 'United Kingdom', 'iso2': 'GB', 'long': -2, 'lat': 54}, {'name': 'United States', 'iso2': 'US', 'long': -97, 'lat': 38}, {'name': 'United States Minor Outlying Islands', 'iso2': 'UM', 'long': 166.6, 'lat': 19.2833}, {'name': 'Uruguay', 'iso2': 'UY', 'long': -56, 'lat': -33}, {'name': 'Uzbekistan', 'iso2': 'UZ', 'long': 64, 'lat': 41}, {'name': 'Vanuatu', 'iso2': 'VU', 'long': 167, 'lat': -16}, {'name': 'Venezuela, Bolivarian Republic of', 'iso2': 'VE', 'long': -66, 'lat': 8}, {'name': 'Vietnam', 'iso2': 'VN', 'long': 106, 'lat': 16}, {'name': 'Virgin Islands, British', 'iso2': 'VG', 'long': -64.5, 'lat': 18.5}, {'name': 'Virgin Islands, U.S.', 'iso2': 'VI', 'long': -64.8333, 'lat': 18.3333}, {'name': 'Wallis and Futuna', 'iso2': 'WF', 'long': -176.2, 'lat': -13.3}, {'name': 'Western Sahara', 'iso2': 'EH', 'long': -13, 'lat': 24.5}, {'name': 'Yemen', 'iso2': 'YE', 'long': 48, 'lat': 15}, {'name': 'Zambia', 'iso2': 'ZM', 'long': 30, 'lat': -15}, {'name': 'Zimbabwe', 'iso2': 'ZW', 'long': 30, 'lat': -20}]

In [13]:
# Obtener todos los países únicos del dataset de Netflix
netflix_countries = sorted({
    country
    for countries in df_clean["country"].dropna()
    for country in countries
})

# Obtener los nombres de países de la API
api_countries = {
    country["name"]
    for country in countries_api
}

# Países de Netflix que NO aparecen en la API
countries_not_found = sorted(
    set(netflix_countries) - api_countries
)

print("Países encontrados en Netflix:", len(netflix_countries))
print("Países no encontrados en la API:", len(countries_not_found))

for country in countries_not_found:
    print(country)

Países encontrados en Netflix: 123
Países no encontrados en la API: 8

East Germany
Iran
Palestine
Soviet Union
Vatican City
Venezuela
West Germany

In [14]:
%pip install python-dotenv

Requirement already satisfied: python-dotenv in ./.venv/lib/python3.14/site-packages (1.2.2)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [15]:
import os
from dotenv import load_dotenv

load_dotenv()

TMDB_API_KEY = os.getenv("TMDB_API_KEY")

print("API key cargada:", TMDB_API_KEY is not None)

API key cargada: True

In [16]:
import requests

# Película de prueba
movie_title = "Louis C.K. 2017"

url = "https://api.themoviedb.org/3/search/movie"

params = {
    "api_key": TMDB_API_KEY,
    "query": movie_title
}

response = requests.get(url, params=params)

print("Status code:", response.status_code)

data = response.json()

print(data.keys())
print("Resultados encontrados:", len(data["results"]))

if data["results"]:
    print(data["results"][0])

Status code: 200
dict_keys(['page', 'results', 'total_pages', 'total_results'])
Resultados encontrados: 1
{'adult': False, 'backdrop_path': '/1rRoyJJBr2QceI1OMCSODy77mwq.jpg', 'genre_ids': [35, 10770], 'id': 449674, 'title': 'Louis C.K. 2017', 'original_language': 'en', 'original_title': 'Louis C.K. 2017', 'overview': 'Louis C.K. muses on religion, eternal love, giving dogs drugs, email fights, teachers and more in a live performance from Washington, D.C.', 'popularity': 1.153, 'poster_path': '/hUa2qgwOXIgEoMatz5UpmxevgG7.jpg', 'release_date': '2017-04-04', 'softcore': False, 'video': False, 'vote_average': 7.262, 'vote_count': 282}

In [17]:
movie_id = 449674

url = f"https://api.themoviedb.org/3/movie/{movie_id}"

params = {
    "api_key": TMDB_API_KEY,
    "append_to_response": "credits"
}

response = requests.get(url, params=params)

print("Status code:", response.status_code)

movie_data = response.json()

print(movie_data.keys())
print(movie_data['credits'].keys())

Status code: 200
dict_keys(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'origin_country', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'softcore', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count', 'credits'])
dict_keys(['cast', 'crew'])

In [18]:
print(movie_data.keys())
print(movie_data['credits'].keys())
print(movie_data['credits']['crew'])

dict_keys(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id', 'imdb_id', 'origin_country', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'production_companies', 'production_countries', 'release_date', 'revenue', 'runtime', 'softcore', 'spoken_languages', 'status', 'tagline', 'title', 'video', 'vote_average', 'vote_count', 'credits'])
dict_keys(['cast', 'crew'])
[{'adult': False, 'gender': 1, 'id': 65916, 'known_for_department': 'Art', 'name': 'Amy Beth Silver', 'original_name': 'Amy Beth Silver', 'popularity': 0.5887, 'profile_path': None, 'credit_id': '63b4a227a9117f05b0dac0d7', 'department': 'Art', 'job': 'Production Design'}, {'adult': False, 'gender': 2, 'id': 52849, 'known_for_department': 'Acting', 'name': 'Louis C.K.', 'original_name': 'Louis C.K.', 'popularity': 3.0536, 'profile_path': '/1ii770zdeX62UFGawTmNr2vddYb.jpg', 'credit_id': '58e40127c3a3684a7901513e', 'department': 'Writing', 'job': 'Writer'}, {'adult': False, 'gender': 2, 'id': 52849, 'known_for_department': 'Acting', 'name': 'Louis C.K.', 'original_name': 'Louis C.K.', 'popularity': 3.0536, 'profile_path': '/1ii770zdeX62UFGawTmNr2vddYb.jpg', 'credit_id': '58e54c9c92514128100303b4', 'department': 'Directing', 'job': 'Director'}, {'adult': False, 'gender': 2, 'id': 2145975, 'known_for_department': 'Directing', 'name': 'Dave Lilling', 'original_name': 'Dave Lilling', 'popularity': 0.3239, 'profile_path': None, 'credit_id': '5bbcb24c925141379a017a62', 'department': 'Directing', 'job': 'Second Unit Director'}]

In [19]:
# Ver países de producción
print("=== COUNTRIES ===")
print(movie_data["production_countries"])


# Ver créditos
print("\n=== CREDITS KEYS ===")
print(movie_data["credits"].keys())


# Ver primeros miembros del cast
print("\n=== CAST ===")
print(movie_data["credits"]["cast"][:3])


# Ver miembros del crew relacionados con dirección
print("\n=== DIRECTORS ===")
directors_tmdb = []
for person in movie_data['credits']['crew']:
    if person['job'] == 'Director':
        directors_tmdb.append(person['job'])

print(directors_tmdb)

=== COUNTRIES ===
[{'iso_3166_1': 'US', 'name': 'United States of America'}]

=== CREDITS KEYS ===
dict_keys(['cast', 'crew'])

=== CAST ===
[{'adult': False, 'gender': 2, 'id': 52849, 'known_for_department': 'Acting', 'name': 'Louis C.K.', 'original_name': 'Louis C.K.', 'popularity': 3.0536, 'profile_path': '/1ii770zdeX62UFGawTmNr2vddYb.jpg', 'cast_id': 0, 'character': 'Self', 'credit_id': '58dcdb3fc3a36822ae00934b', 'order': 0}]

=== DIRECTORS ===
['Director']

In [20]:
import requests
import pandas as pd


def get_tmdb_data(row):
    """
    Consulta TMDB usando el título y tipo de contenido.
    Retorna director, cast y country encontrados.
    """

    title = row["title"]
    content_type = row["type"]

    # Buscar título en TMDB
    search_endpoint = (
        "https://api.themoviedb.org/3/search/movie"
        if content_type == "Movie"
        else "https://api.themoviedb.org/3/search/tv"
    )

    params = {
        "api_key": TMDB_API_KEY,
        "query": title
    }

    response = requests.get(search_endpoint, params=params)

    if response.status_code != 200:
        return {
            "director": None,
            "cast": None,
            "country": None
        }

    results = response.json().get("results", [])

    # Si no encuentra el título
    if not results:
        return {
            "director": None,
            "cast": None,
            "country": None
        }

    tmdb_id = results[0]["id"]

    # Obtener detalles
    details_endpoint = (
        f"https://api.themoviedb.org/3/movie/{tmdb_id}"
        if content_type == "Movie"
        else f"https://api.themoviedb.org/3/tv/{tmdb_id}"
    )

    details_params = {
        "api_key": TMDB_API_KEY,
        "append_to_response": "credits"
    }

    details_response = requests.get(
        details_endpoint,
        params=details_params
    )

    if details_response.status_code != 200:
        return {
            "director": None,
            "cast": None,
            "country": None
        }

    data = details_response.json()

    # Obtener directores
    directors = [
        person["name"]
        for person in data.get("credits", {}).get("crew", [])
        if person.get("job") == "Director"
    ]

    # Obtener actores principales
    cast = [
        person["name"]
        for person in data.get("credits", {}).get("cast", [])[:10]
    ]

    # Obtener países
    countries = [
        country["name"]
        for country in data.get("production_countries", [])
    ]

    return {
        "director": directors if directors else None,
        "cast": cast if cast else None,
        "country": countries if countries else None
    }

In [21]:
test_row = df_clean.iloc[5541]

result = get_tmdb_data(test_row)

result

{'director': ['Louis C.K.'],
 'cast': ['Louis C.K.'],
 'country': ['United States of America']}

In [22]:
# Seleccionar registros donde falta algún dato que queremos completar
missing_data_sample = df_clean[
    df_clean["director"].isna() |
    df_clean["cast"].isna() |
    df_clean["country"].isna()
].head(5)

display(missing_data_sample[["title", "type", "director", "cast", "country"]])

,title,type,director,cast,country
0,Dick Johnson Is Dead,Movie,[Kirsten Johnson],<NA>,[United States]
1,Blood & Water,TV Show,<NA>,"[Ama Qamata, Khosi Ngema, Gail Mabalane, Thaba...",[South Africa]
2,Ganglands,TV Show,[Julien Leclercq],"[Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nab...",<NA>
3,Jailbirds New Orleans,TV Show,<NA>,<NA>,<NA>
4,Kota Factory,TV Show,<NA>,"[Mayur More, Jitendra Kumar, Ranjan Raj, Alam ...",[India]

In [23]:
for index, row in missing_data_sample.iterrows():
    print("=" * 60)
    print("Título:", row["title"])
    print("Tipo:", row["type"])

    tmdb_result = get_tmdb_data(row)

    print(tmdb_result)

============================================================
Título: Dick Johnson Is Dead
Tipo: Movie
{'director': ['Kirsten Johnson'], 'cast': ['Richard Johnson', 'Kirsten Johnson', 'Isla Sierck', 'Jed Sierck', 'Felix Torres', 'Viva Torres', 'Raymond Damazo', 'Michael Hilow', 'Michael Melton', 'Joanne Reiner Tucker'], 'country': ['United States of America']}
============================================================
Título: Blood & Water
Tipo: TV Show
{'director': None, 'cast': ['Ama Qamata', 'Khosi Ngema', 'Gail Mabalane', 'Dillon Windvogel', 'Thabang Molaba', 'Arno Greeff', 'Natasha Thahane', 'Mekaila Mathys', 'Greteli Fincham', 'Leroy Panashe Siyafa'], 'country': ['South Africa']}
============================================================
Título: Ganglands
Tipo: TV Show
{'director': ['Julien Leclercq'], 'cast': ['Sami Bouajila', 'Tracy Gotoas', 'Salim Kéchiouche', 'Samuel Jouy', 'Aron Kto', 'Lola Le Lann'], 'country': ['Belgium', 'France']}
============================================================
Título: Jailbirds New Orleans
Tipo: TV Show
{'director': None, 'cast': None, 'country': ['United States of America']}
============================================================
Título: Kota Factory
Tipo: TV Show
{'director': ['Pratish Mehta', 'Raghav Subbu'], 'cast': ['Jitendra Kumar', 'Mayur More', 'Ranjan Raj', 'Alam Khan', 'Ahsaas Channa', 'Revathi Pillai'], 'country': ['India']}

In [24]:
# Tomar registros que tienen país en Netflix
sample_countries = df_clean[
    df_clean["country"].notna()
].head(100)

tmdb_country_names = set()

for index, row in sample_countries.iterrows():

    result = get_tmdb_data(row)

    if result["country"]:
        for country in result["country"]:
            tmdb_country_names.add(country)


print("Países encontrados en TMDB:")
for country in sorted(tmdb_country_names):
    print(country)

Países encontrados en TMDB:
Argentina
Australia
Belgium
Burkina Faso
Canada
China
Czech Republic
Ethiopia
Finland
France
Germany
Ghana
Hong Kong
India
Italy
Japan
Mexico
Netherlands
Nigeria
Romania
Russia
Singapore
South Africa
South Korea
Spain
Thailand
Turkey
United Kingdom
United States of America
Venezuela

In [25]:
missing_country = df_clean[df_clean["country"].isna()].copy()

print("Registros sin país:", len(missing_country))

Registros sin país: 831

In [26]:
import requests
import time

session = requests.Session()

def get_tmdb_country(title, content_type):
    
    # Endpoint de búsqueda
    if content_type == "Movie":
        search_url = "https://api.themoviedb.org/3/search/movie"
    else:
        search_url = "https://api.themoviedb.org/3/search/tv"

    params = {
        "api_key": TMDB_API_KEY,
        "query": title
    }

    try:
        response = session.get(
            search_url,
            params=params,
            timeout=10
        )

        response.raise_for_status()

        results = response.json().get("results", [])

        # No se encontró el título
        if not results:
            return None

        # Tomamos el primer resultado
        tmdb_id = results[0]["id"]

        # Endpoint de detalles
        if content_type == "Movie":
            details_url = f"https://api.themoviedb.org/3/movie/{tmdb_id}"
        else:
            details_url = f"https://api.themoviedb.org/3/tv/{tmdb_id}"

        response = session.get(
            details_url,
            params={"api_key": TMDB_API_KEY},
            timeout=10
        )

        response.raise_for_status()

        data = response.json()

        countries = data.get("production_countries", [])

        return [
            country["name"]
            for country in countries
        ]

    except requests.exceptions.RequestException:
        return None

In [27]:
for index, row in missing_country.iterrows():

    countries = get_tmdb_country(
        row["title"],
        row["type"]
    )

    if countries:
        df_clean.at[index, "country"] = countries

    print(
        f"{index}: {row['title']} -> {countries}"
    )

    time.sleep(0.05)

2: Ganglands -> ['Belgium', 'France']
3: Jailbirds New Orleans -> ['United States of America']
5: Midnight Mass -> ['United States of America']
6: My Little Pony: A New Generation -> ['Canada', 'Ireland']
10: Vendetta: Truth, Lies and The Mafia -> ['Italy', 'United Kingdom']
11: Bangkok Breaking -> ['Thailand']
13: Confessions of an Invisible Girl -> ['Brazil']
14: Crime Stories: India Detectives -> ['United Kingdom']
16: Europe's Most Dangerous Man: Otto Skorzeny in Spain -> ['Spain']
18: Intrusion -> ['United States of America']
19: Jaguar -> ['Spain']
20: Monsters Inside: The 24 Faces of Billy Milligan -> []
22: Avvai Shanmughi -> None
23: Go! Go! Cory Carson: Chrissy Takes the Wheel -> ['United States of America']
26: Minsara Kanavu -> ['India']
30: Ankahi Kahaniya -> ['India']
31: Chicago Party Aunt -> ['United States of America']
33: Squid Game -> ['South Korea']
34: Tayo and Little Wizards -> ['South Korea']
35: The Father Who Moves Mountains -> ['Romania', 'Sweden']
36: The Stronghold -> ['France']
45: My Heroes Were Cowboys -> ['United States of America']
47: The Smart Money Woman -> ['Nigeria']
64: Nightbooks -> ['Canada', 'United States of America']
68: Schumacher -> ['Germany']
70: Too Hot To Handle: Latino -> ['Mexico']
71: A StoryBots Space Adventure -> []
74: The World's Most Amazing Vacation Rentals -> []
75: You vs. Wild: Out Cold -> []
77: Little Singham - Black Shadow -> []
78: Tughlaq Durbar -> ['India']
79: Tughlaq Durbar (Telugu) -> None
80: Firedrake the Silver Dragon -> ['Belgium', 'Germany']
83: Metal Shop Masters -> []
85: Pokémon Master Journeys: The Series -> ['Japan']
86: Prey -> ['United States of America']
87: Titipo Titipo -> ['South Korea']
88: Blood Brothers: Malcolm X & Muhammad Ali -> ['United States of America', 'United Kingdom']
89: Mighty Raju -> ['India']
93: JJ+E -> ['Sweden']
100: Tobot Galaxy Detectives -> []
102: Countdown: Inspiration4 Mission to Space -> ['United States of America']
103: Shadow Parties -> []
110: Money Heist: From Tokyo to Berlin -> ['Spain']
112: Worth -> ['Canada', 'United Kingdom', 'United States of America']
113: Afterlife of the Party -> ['United States of America']
119: Here and There -> ['Canada']
121: Hotel Del Luna -> ['South Korea']
123: Luv Kushh -> None
128: Agatha Christie's Crooked House -> ['United Kingdom', 'United States of America']
130: Barbie Big City Big Dreams -> ['United States of America']
132: Brave Animated Series -> ['Taiwan']
147: How to Be a Cowboy -> ['United States of America']
148: HQ Barbers -> []
165: Oldsters -> ['Chile']
180: The Nutty Professor II: The Klumps -> ['United States of America']
181: Turning Point: 9/11 and the War on Terror -> ['United States of America']
185: Untold: Crime & Penalties -> ['United States of America']
186: Hometown Cha-Cha-Cha -> ['South Korea']
187: The Ingenuity of the Househusband -> ['Japan']
189: Bread Barbershop -> ['South Korea']
194: Deadly Sins -> ['United States of America']
196: He's All That -> ['United States of America']
197: I Heart Arlo -> ['United States of America']
213: RIDE ON TIME -> ['Japan']
214: SAS: Rise of the Black Swan -> ['Hungary', 'Netherlands', 'Switzerland', 'United Kingdom']
218: Titletown High -> ['United States of America']
221: Bob Ross: Happy Accidents, Betrayal & Greed -> ['Netherlands', 'United States of America']
222: Clickbait -> ['Australia', 'United States of America']
223: John of God: The Crimes of a Spiritual Healer -> ['Brazil']
224: Motel Makeover -> ['Canada']
225: Open Your Eyes -> ['Poland']
226: Post Mortem: No One Dies in Skarnes -> ['Norway']
230: The River Runner -> []
234: Oggy Oggy -> ['France', 'Canada']
235: Untold: Caitlyn Jenner -> ['United States of America']
236: Boomika -> ['India']
237: Boomika (Hindi) -> None
238: Boomika (Malayalam) -> None
239: Boomika (Telugu) -> None
240: The Witcher: Nightmare of the Wolf -> ['Poland', 'South Korea', 'United States of America']
242: Comedy Premium League -> ['India']
243: Everything Will Be Fine -> []
244: Gunshot -> []
245: Korean Cold Noodle Rhapsody -> ['South Korea']
246: Man in Love -> ['China', 'Hong Kong', 'Taiwan', 'United States of America']
248: The Chair -> ['United States of America']
249: The Loud House Movie -> ['United States of America']
250: A Faraway Land -> ['Faeroe Islands', 'Philippines']
252: Black Island -> ['United Kingdom']
255: Memories of a Murderer: The Nilsen Tapes -> ['United Kingdom']
256: Nneka The Pretty Serpent -> []
257: O Kadhal Kanmani -> ['India']
258: Out of my league -> ['Italy']
260: The Defeated -> ['Japan']
261: The Secret Diary of an Exchange Student -> ['Brazil']
262: Untold: Deal With the Devil -> ['United States of America']
268: Unroyal -> ['Nigeria']
287: I Need Romance -> ['South Korea']
294: Takizawa Kabuki ZERO 2020 The Movie -> []
309: Car Masters: Rust to Riches -> ['United States of America']
318: Shiny_Flakes: The Teenage Drug Lord -> ['Germany']
320: Top Secret UFO Projects: Declassified -> []
331: Darwin’s Game -> ['Japan']
336: Friday Night Lights -> ['United States of America']
339: I missed you: Director's Cut -> ['Taiwan']
362: The Lost Café -> ['Nigeria', 'Norway']
363: The Vault -> ['France', 'Spain']
364: Centaurworld -> ['Canada', 'United States of America']
367: I'm Glad I Did -> ['Turkey']
368: Khawatir -> None
369: Myth & Mogul: John DeLorean -> ['United States of America']
371: Pomegranates and Myrrh -> ['France', 'Germany', 'Kuwait', 'Palestinian Territory']
372: Rurouni Kenshin: The Beginning -> ['Japan']
373: The Last Mercenary -> ['France']
375: Resort to Love -> ['United States of America']
376: Transformers: War for Cybertron: Kingdom -> ['Canada', 'Japan', 'United States of America']
379: Tattoo Redo -> ['United States of America']
381: The Snitch Cartel: Origins -> ['Colombia']
384: Hostage House -> ['United States of America']
387: Mimi -> ['Slovakia']
388: Plastic Cup Boyz: Laughing My Mask Off! -> ['United States of America']
394: African America -> ['South Africa']
395: Bankrolled -> ['Mexico']
396: Blood Red Sky -> ['Germany', 'United Kingdom']
397: Feels Like Ishq -> ['India']
398: Kingdom: Ashin of the North -> ['South Korea']
399: Masters of the Universe: Revelation -> ['United States of America']
400: Revelations: The Masters of the Universe: Revelation Aftershow -> ['United States of America']
404: 9to5: The Story of a Movement -> ['United States of America']
405: Chhota Bheem - Dinosaur World -> []
406: Chhota Bheem - Neeli Pahaadi -> []
407: Chhota Bheem & Ganesh -> []
408: Chhota Bheem & Krishna: Mayanagari -> ['India']
409: Chhota Bheem & Krishna: Pataliputra- City of the Dead -> ['India']
411: Chhota Bheem And The Crown of Valhalla -> ['India']
412: Chhota Bheem and the Incan Adventure -> []
413: Chhota Bheem and The ShiNobi Secret -> ['India']
414: Chhota Bheem Aur Hanuman -> ['India']
416: Chhota Bheem aur Krishna vs Zimbara -> None
417: Chhota Bheem in African Safari -> []
418: Chhota Bheem Ka Roosi Romanch -> []
419: Chhota Bheem: Bheem vs Aliens -> []
420: Chhota Bheem: Dholakpur to Kathmandu -> []
421: Chhota Bheem: Dus Pe Dus -> []
422: Chhota Bheem: Journey to Petra -> ['India']
423: Chhota Bheem: Master of Shaolin -> ['India']
424: Chhota Bheem: The Rise of Kirmada -> ['India']
427: Wannabe Courageous -> ['Egypt']
428: Words Bubble Up Like Soda Pop -> ['Japan']
430: Sexy Beasts -> ['United Kingdom']
431: Too Hot to Handle: Brazil -> ['Mexico', 'Brazil']
432: Trollhunters: Rise of the Titans -> ['United States of America']
435: Touch Your Heart -> ['South Korea']
438: 2 Weeks in Lagos -> ['Nigeria']
441: Fear Street Part 3: 1666 -> ['United States of America']
443: La ley de Herodes -> ['Mexico']
444: Naomi Osaka -> ['United States of America']
454: Cheech & Chong's Still Smokin -> ['United States of America']
455: Emicida: AmarElo - Live in São Paulo -> ['Brazil']
458: My Amanda -> ['Philippines']
461: The Unknown Saint -> ['Qatar', 'Morocco', 'France']
464: Gunpowder Milkshake -> ['France', 'Germany', 'United States of America']
465: Heist -> ['Spain']
466: My Unorthodox Life -> ['United States of America']
467: Private Network: Who Killed Manuel Buendía? -> ['Mexico']
468: The Guide to the Perfect Family -> ['Canada']
470: Bridgerton - The Afterparty -> None
471: Day of Destiny -> ['Nigeria']
475: The Stand-Up -> ['United States of America']
476: The Tour -> ['France', 'Italy']
479: Fear Street Part 2: 1978 -> ['United States of America']
480: Finding Hubby -> ['Nigeria']
481: How I Became a Superhero -> ['France']
482: How to Become a Tyrant -> ['United States of America']
483: Last Summer -> ['France']
484: Lee Su-geun: The Sense Coach -> ['South Korea']
485: Lethal Love -> ['United States of America']
487: The Cook of Castamar -> ['Spain', 'United States of America']
490: Elize Matsunaga: Once Upon a Crime -> ['Brazil']
495: Awon Boyz -> ['Nigeria']
497: Cat People -> []
498: Clash -> ['United States of America', 'United Kingdom']
500: Major Grom: Plague Doctor -> ['Russia']
501: Mama Drama -> ['Nigeria']
504: The War Next-door -> ['United States of America']
505: Therapy -> []
507: Three Thieves -> ['Russia']
546: You Are My Spring -> ['South Korea']
549: Big Timber -> ['Canada']
550: Fear Street Part 1: 1994 -> ['United States of America']
552: Holiday on Mars -> ['Italy']
560: Audible -> ['United States of America']
570: Dynasty Warriors -> ['China', 'Hong Kong', 'Japan']
571: Generation 56k -> ['Italy']
577: Masameer County -> ['Saudi Arabia']
580: Mobile Suit Gundam Hathaway -> ['Japan']
586: Pet Sematary 2 -> ['United States of America']
587: Quarantine Tales -> []
590: Sailor Moon Crystal -> ['Japan']
616: Working Title -> ['United Kingdom']
619: Deranged -> ['Canada']
621: Legend of Exorcism -> ['China']
623: Mommy Issues -> ['Philippines']
624: Prime Time -> ['India']
626: Sophie: A Murder in West Cork -> ['United Kingdom']
629: A Way Back Home -> []
632: Wanted -> ['United States of America']
633: Into the Wind -> ['United States of America']
637: Ray -> ['United States of America']
639: Godzilla Singular Point -> ['Japan']
640: Jiva! -> ['South Africa']
641: Sisters on Track -> ['United States of America']
644: Good on Paper -> ['United States of America']
645: Murder by the Coast -> ['Spain']
646: The House of Flowers: The Movie -> ['Mexico']
647: The Parisian Agency: Exclusive Properties -> ['France']
649: Broken -> ['Russia']
652: Osuofia in London II -> None
653: This Is Pop -> ['United States of America']
658: Nevertheless, -> ['South Korea']
663: Charité at War -> None
666: Gameboys Level-Up Edition -> ['Philippines']
670: Mobile Suit Gundam II: Soldiers of Sorrow -> ['Japan']
671: Mobile Suit Gundam III: Encounters in Space -> ['Japan']
672: Mobile Suit Gundam: Char's Counterattack -> ['Japan']
683: A Family -> ['United States of America']
687: Jagame Thandhiram -> ['India']
689: Mobile Suit Gundam I -> ['Japan']
690: Rurouni Kenshin: The Final -> ['Japan']
691: So Not Worth It -> ['South Korea']
692: The Rational Life -> ['China']
693: Ali & Ratu Ratu Queens -> ['Indonesia']
695: Besieged Bread -> ['Syrian Arab Republic']
697: Elite Short Stories: Carla Samuel -> ['Spain']
700: Record of Ragnarok -> ['Japan']
704: A Man For The Week End -> None
706: Elite Short Stories: Omar Ander Alexis -> ['Spain']
707: Let's Eat -> ['South Korea']
710: Penguin Town -> ['South Africa']
712: Silver Skates -> ['Russia']
714: Beyond Evil -> ['South Korea']
715: Elite Short Stories: Nadia Guzmán -> ['Spain']
717: Headspace: Unwind Your Mind -> ['United States of America']
720: Rhyme Time Town -> ['United States of America']
725: Elite Short Stories: Guzmán Caye Rebe -> ['Spain']
729: Bling Empire - The Afterparty -> None
730: Cobra Kai - The Afterparty -> None
732: To All the Boys: Always and Forever - The Afterparty -> ['United States of America']
738: Trese After Dark -> ['Philippines']
751: Guru Aur Bhole -> ['India']
759: Fireplace 4K: Classic Crackling Fireplace from Fireplace for Your Home -> None
760: Fireplace 4K: Crackling Birchwood from Fireplace for Your Home -> ['United States of America']
761: Human: The World Within -> []
771: Pretty Guardian Sailor Moon Eternal The Movie -> None
781: Black Holes | The Edge of All We Know -> ['United States of America']
805: Racket Boys -> ['South Korea']
806: Seven Souls in the Skull Castle: Season Moon Jogen -> []
807: Seven Souls in the Skull Castle: Season Moon Kagen -> []
811: Super Monsters: Once Upon a Rhyme -> ['United States of America']
815: The Girl King -> ['Canada', 'Finland', 'France', 'Germany', 'Sweden']
827: One Lagos Night -> ['Nigeria']
829: Dog Gone Trouble -> ['Canada']
831: The Least Expected Day: Inside the Movistar Team 2019 -> ['Spain']
832: Word of Honor -> ['China']
835: Eden -> ['Taiwan', 'United States of America']
841: Gatao - The Last Stray -> ['Taiwan']
842: High on the Hog: How African American Cuisine Transformed America -> ['United States of America']
844: Nail Bomber: Manhunt -> ['United Kingdom']
845: A Place in the Stars -> ['Nigeria']
847: Mad for Each Other -> ['South Korea']
849: Sam Smith: Love Goes - Live at Abbey Road Studios -> ['United States of America']
851: 99 Songs (Tamil) -> None
852: 99 Songs (Telugu) -> None
854: Creating an Army of the Dead -> ['United States of America']
856: Strain -> ['United States of America']
858: 678 -> ['Egypt']
861: Little Singham Future mein Satakli -> []
864: Taxi No. 9211 -> ['India']
875: Love or Money -> ['United States of America']
886: The Mystic River -> []
888: The Upshaws - The Afterparty -> ['United States of America']
893: Wave of Cinema: Filosofi Kopi -> ['Indonesia']
897: Use For My Talent -> ['China']
898: Dear Affy -> ['Nigeria']
912: The Circle - The Afterparty -> ['United States of America']
923: Trash Truck -> ['United States of America']
925: Angelina Ballerina -> ['United Kingdom']
927: Barney and Friends -> ['United States of America']
929: Dead Again in Tombstone -> ['United States of America']
936: Miniforce: Super Dino Power -> ['South Korea']
937: Motu Patlu in Dragon's World -> ['India']
938: Motu Patlu in the Game of Zones -> ['India']
939: Motu Patlu in Wonderland -> []
940: Motu Patlu: Deep Sea Adventure -> ['India']
941: Motu Patlu: Mission Moon -> ['India']
957: Pet Stars -> ['United States of America']
958: Seven -> ['Saudi Arabia', 'Egypt']
960: The Innocent -> ['Spain']
961: The Mitchells vs. The Machines -> ['Hong Kong', 'United States of America']
963: The Unremarkable Juanquini -> ['Colombia']
964: Things Heard & Seen -> ['United States of America']
965: Yasuke -> ['Japan']
967: Headspace Guide to Sleep -> ['United Kingdom', 'United States of America']
987: Legal Hash -> None
992: Perfume Imaginary Museum “Time Warp” -> ['Japan']
1000: Wild Dog -> ['India']
1005: Keymon and Nani in Space Adventure -> ['India']
1006: Motu Patlu Dino Invasion -> ['India']
1007: Motu Patlu in Octupus World -> None
1008: Motu Patlu VS Robo Kids -> None
1009: Rudra: Secret of the Black Moon -> ['India']
1010: Rudra: The Rise of King Pharaoh -> ['India']
1025: Bakugan: Geogan Rising -> ['Canada', 'Japan', 'United States of America']
1028: Dad Stop Embarrassing Me - The Afterparty -> ['United States of America']
1038: Dancing Angels -> None
1054: Wave of Cinema: One Day We'll Talk About Today -> None
1056: Ajaibnya Cinta -> None
1071: Motu Patlu in Hong Kong: Kung Fu Kings 3 -> []
1072: Motu Patlu in the City of Gold -> []
1073: Motu Patlu Kung Fu Kings 4 The Challenge of Kung Fu Brothers -> ['India']
1074: Motu Patlu the Superheroes – Super Villains from Mars -> []
1076: Shiva VS Autobots -> []
1077: Shiva: Journey to Plunotaria -> ['India']
1078: Shiva: The Secret World Of Vedas City -> []
1082: Don't be the First one -> ['South Korea']
1092: Dolly Parton: A MusiCares Tribute -> ['United States of America']
1094: The Wedding Coach -> ['United States of America']
1095: This Is a Robbery: The World's Biggest Art Heist -> ['United States of America']
1096: The Last Kids on Earth: Happy Apocalypse to You -> ['Canada']
1116: Glimpses of a Future -> ['Lebanon']
1130: Seven Souls in the Skull Castle: Season Bird -> []
1132: Seven Souls in the Skull Castle: Season Wind -> []
1159: Black Is Beltza -> ['Spain']
1180: Alien TV -> ['Australia']
1183: Reframe THEATER EXPERIENCE with you -> ['Japan']
1193: Wave of Cinema: 90's Generation -> ['Indonesia']
1207: Audrey -> ['United Kingdom', 'United States of America']
1214: Quiet -> ['United States of America']
1224: Last Chance U: Basketball -> ['United States of America']
1225: Marriage or Mortgage -> ['United States of America']
1235: Pokémon Journeys: The Series -> ['Japan']
1246: A Perfect Day For Arsenide -> ['Hong Kong']
1247: Banyuki -> ['Japan']
1249: Blanche Gardin: The All-Nighter -> None
1250: Connected -> ['China', 'Hong Kong']
1255: Seven Souls in the Skull Castle 2011 -> None
1262: Ginny & Georgia - The Afterparty -> ['United States of America']
1271: The Last Bastion -> []
1276: M8 - When Death Rescues Life -> ['Brazil']
1289: Wave of Cinema: Surat dari Timur -> ['Indonesia']
1299: Thus Spoke Kishibe Rohan -> ['Japan']
1381: Hire a Woman -> []
1382: She Is -> []
1418: Chris Rock Total Blackout: The Tamborine Extended Cut -> ['United States of America']
1436: Ratones Paranoicos: The Band that Rocked Argentina -> ['Argentina']
1442: Korean Pork Belly Rhapsody -> ['South Korea']
1462: Running Man -> ['South Korea']
1471: Best of Stand-Up 2020 -> ['United States of America']
1482: Transformers: War for Cybertron: Earthrise -> ['Canada', 'Japan', 'United States of America']
1518: Ma Rainey's Black Bottom: A Legacy Brought to Screen -> ['United States of America']
1531: The Wedding Shaman -> ['Indonesia']
1533: BREAK IT ALL: The History of Rock in Latin America -> ['Argentina', 'Colombia', 'Mexico', 'Uruguay']
1556: A Trash Truck Christmas -> ['United States of America']
1564: Futmalls.com -> ['Taiwan']
1581: Super Monsters: Santa’s Super Monster Helpers -> []
1585: Manhunt: Deadly Games -> ['United States of America']
1596: The Great British Baking Show: Holidays -> None
1600: Chico Bon Bon and the Very Berry Holiday -> ['United States of America']
1652: Andhaghaaram -> ['India']
1668: Heart & Soul -> ['Portugal']
1723: Bakugan: Armored Alliance -> ['Canada', 'Japan', 'United States of America']
1744: The Beginning of Life -> ['China']
1745: Ya no estoy aquí: Una conversación entre Guillermo del Toro y Alfonso Cuarón -> []
1778: Kongsuni and Friends -> ['South Korea']
1786: La Gran Ilusión -> ['Spain']
1828: Unsolved Mysteries -> []
1889: Pat a Pat Como -> ['South Korea']
1890: Qurious Como -> ['South Korea']
1892: A Go! Go! Cory Carson Halloween -> []
1914: Journey of an African Colony -> []
1919: The American Game -> ['United States of America']
1952: Mighty Little Bheem -> ['India']
1953: My Mother's Wound -> []
1956: Zulu Man in Japan -> ['South Africa']
1968: High & Low The Worst -> ['Japan']
1973: Fukrey Boyzzz -> []
1983: Dragon's Dogma -> ['Japan']
1986: Nee Enge En Anbe -> ['India']
1992: Dr Jason Leong Hashtag Blessed -> ['Malaysia']
2004: Wish Upon a Unicorn -> ['United States of America', 'Canada']
2014: Wonho Chung: Live in New York -> []
2040: Transformers: Cyberverse -> ['Canada', 'Ireland', 'United States of America']
2058: The Witcher: A Look Inside the Episodes -> []
2101: Baewatch: Parental Guidance -> []
2114: Little Singham: Kaal Ka Badla -> []
2123: Dérè: An African Tale -> ['Nigeria']
2128: Beyond the Boundary: ICC Women's T20 World Cup Australia 2020 -> ['United Arab Emirates']
2147: Diamonds in the Sky -> ['Nigeria']
2152: Selling Sunset -> ['United States of America']
2164: Sin City -> ['United States of America']
2166: A Go! Go! Cory Carson Summer Camp -> ['United States of America']
2182: Tumi or not Tumi -> []
2194: Unlucky Ploy -> ['Thailand']
2222: Street Food: Latin America -> ['United States of America']
2236: Little Singham: Legend of Dugabakka -> []
2252: Your Excellency -> ['Mexico']
2261: Jim Jefferies: Intolerant -> ['United States of America']

In [28]:
print("============================================")
print("      AUDITORÍA FINAL DEL DATASET")
print("============================================")

# 1. Información general
print("\n=== INFORMACIÓN GENERAL ===")
df_clean.info()

# 2. Valores nulos
print("\n=== VALORES NULOS ===")
print(df_clean.isna().sum())

# 3. Porcentaje de nulos
print("\n=== PORCENTAJE DE NULOS ===")
print(
    (df_clean.isna().mean() * 100)
    .round(2)
    .sort_values(ascending=False)
)

# ============================================================
# DUPLICADOS
# ============================================================

print("\n=== FILAS DUPLICADAS ===")

# Convertimos temporalmente las listas a texto para poder
# comprobar duplicados de filas completas.
df_duplicates_check = df_clean.copy()

for column in ["director", "cast", "country", "listed_in"]:
    df_duplicates_check[column] = df_duplicates_check[column].apply(
        lambda x: tuple(x) if isinstance(x, list) else x
    )

print(
    "Filas completamente duplicadas:",
    df_duplicates_check.duplicated().sum()
)


# ============================================================
# DUPLICADOS POR show_id
# ============================================================

print("\n=== show_id DUPLICADOS ===")

duplicated_ids = df_clean[
    df_clean["show_id"].duplicated(keep=False)
]

print("show_id duplicados:", len(duplicated_ids))

if len(duplicated_ids) > 0:
    display(
        duplicated_ids[
            ["show_id", "title", "type"]
        ].sort_values("show_id")
    )
else:
    print("No existen show_id duplicados.")

# 6. Valores de type
print("\n=== TYPE ===")
print(df_clean["type"].value_counts(dropna=False))

# 7. Ratings
print("\n=== RATING ===")
print(df_clean["rating"].value_counts(dropna=False))

# 8. Duraciones
print("\n=== DURATION ===")
print(df_clean["duration"].value_counts(dropna=False).head(30))

# 9. Tipos de datos
print("\n=== TIPOS DE DATOS ===")
print(df_clean.dtypes)

============================================
      AUDITORÍA FINAL DEL DATASET
============================================

=== INFORMACIÓN GENERAL ===
<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       8557 non-null   object
 6   date_added    8709 non-null   datetime64[us]
 7   release_year  8807 non-null   int64
 8   rating        8800 non-null   str
 9   duration      8807 non-null   str
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   str
dtypes: datetime64[us](1), int64(1), object(4), str(6)
memory usage: 825.8+ KB

=== VALORES NULOS ===
show_id            0
type               0
title              0
director        2634
cast             825
country          250
date_added        98
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

=== PORCENTAJE DE NULOS ===
director        29.91
cast             9.37
country          2.84
date_added       1.11
rating           0.08
show_id          0.00
type             0.00
title            0.00
release_year     0.00
duration         0.00
listed_in        0.00
description      0.00
dtype: float64

=== FILAS DUPLICADAS ===
Filas completamente duplicadas: 0

=== show_id DUPLICADOS ===
show_id duplicados: 0
No existen show_id duplicados.

=== TYPE ===
type
Movie      6131
TV Show    2676
Name: count, dtype: int64

=== RATING ===
rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
NaN            7
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

=== DURATION ===
duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
94 min        146
97 min        146
93 min        146
91 min        144
95 min        137
96 min        130
92 min        129
102 min       122
98 min        120
99 min        118
88 min        116
101 min       116
103 min       114
106 min       111
100 min       108
89 min        106
104 min       104
86 min        103
105 min       101
87 min        101
107 min        98
110 min        97
4 Seasons      95
108 min        87
116 min        80
112 min        74
Name: count, dtype: int64

=== TIPOS DE DATOS ===
show_id                    str
type                       str
title                      str
director                object
cast                    object
country                 object
date_added      datetime64[us]
release_year             int64
rating                     str
duration                   str
listed_in               object
description                str
dtype: object

In [29]:
# ============================================================
# COMPLETAR DIRECTORES FALTANTES CON TMDB
# USANDO TÍTULO + RELEASE YEAR
# ============================================================

movies_missing_director = df_clean[
    (df_clean["type"] == "Movie") &
    (df_clean["director"].isna())
].copy()

print(
    "Películas sin director antes de TMDB:",
    len(movies_missing_director)
)

directors_found = 0
directors_not_found = 0

for index, row in movies_missing_director.iterrows():

    result = get_tmdb_data(row)

    if result["director"]:

        df_clean.at[index, "director"] = result["director"]

        directors_found += 1

    else:
        directors_not_found += 1


print("\n============================================")
print("RESULTADO")
print("============================================")

print("Directores encontrados:", directors_found)
print("Directores no encontrados:", directors_not_found)

print(
    "Películas sin director después de TMDB:",
    df_clean[
        (df_clean["type"] == "Movie") &
        (df_clean["director"].isna())
    ].shape[0]
)

Películas sin director antes de TMDB: 188

============================================
RESULTADO
============================================
Directores encontrados: 115
Directores no encontrados: 73
Películas sin director después de TMDB: 73

In [30]:
# ============================================================
# PREPARAR date_added PARA MYSQL
# ============================================================

# Asegurar que la columna sea datetime
df_clean["date_added"] = pd.to_datetime(
    df_clean["date_added"],
    errors="coerce"
)

# Como MySQL utilizará DATE, eliminamos la parte de hora
df_clean["date_added"] = df_clean["date_added"].dt.date

print("Tipo de dato de date_added:")
print(df_clean["date_added"].dtype)

print("\nPrimeras fechas:")
print(df_clean["date_added"].head())

print("\nFechas nulas:")
print(df_clean["date_added"].isna().sum())

Tipo de dato de date_added:
object

Primeras fechas:
0    2021-09-25
1    2021-09-24
2    2021-09-24
3    2021-09-24
4    2021-09-24
Name: date_added, dtype: object

Fechas nulas:
98

In [31]:
# Verificar que las fechas tienen el formato esperado
display(
    df_clean[["show_id", "title", "date_added"]].head(20)
)

   show_id                                              title  date_added
0       s1                               Dick Johnson Is Dead  2021-09-25
1       s2                                      Blood & Water  2021-09-24
2       s3                                          Ganglands  2021-09-24
3       s4                              Jailbirds New Orleans  2021-09-24
4       s5                                       Kota Factory  2021-09-24
5       s6                                      Midnight Mass  2021-09-24
6       s7                   My Little Pony: A New Generation  2021-09-24
7       s8                                            Sankofa  2021-09-24
8       s9                      The Great British Baking Show  2021-09-24
9      s10                                       The Starling  2021-09-24
10     s11                Vendetta: Truth, Lies and The Mafia  2021-09-24
11     s12                                   Bangkok Breaking  2021-09-23
12     s13                                       Je Suis Karl  2021-09-23
13     s14                   Confessions of an Invisible Girl  2021-09-22
14     s15                    Crime Stories: India Detectives  2021-09-22
15     s16                                  Dear White People  2021-09-22
16     s17  Europe's Most Dangerous Man: Otto Skorzeny in ...  2021-09-22
17     s18                                    Falsa identidad  2021-09-22
18     s19                                          Intrusion  2021-09-22
19     s20                                             Jaguar  2021-09-22